import { radii } from "./radii.js";
import { spacing } from "./spacing.js";
import { typography } from "./typography.js";

const CSS_PIXELS_PER_REM = 16;

function rem(value: number) {
  return `${value / CSS_PIXELS_PER_REM}rem`;
}

/** Build the Tailwind v4 theme from the portable token objects. */
export function buildTailwindThemeCss() {
  const variables = [
    `--spacing: ${rem(spacing["1"])};`,
    ...Object.entries(radii).map(
      ([token, value]) => `--radius-${token}: ${rem(value)};`,
    ),
    ...Object.entries(typography.sizes).flatMap(([token, metrics]) => [
      `--text-${token}: ${rem(metrics.fontSize)};`,
      `--text-${token}--line-height: ${rem(metrics.lineHeight)};`,
    ]),
    ...Object.entries(typography.weights).map(
      ([token, value]) => `--font-weight-${token}: ${value};`,
    ),
  ];

  return `/* Generated by scripts/write-tailwind-theme.mjs. Do not edit directly. */\n@theme {\n${variables.map((variable) => `  ${variable}`).join("\n")}\n}\n`;
}
