# Phase 2: read-only. `data` blocks let Terraform look things up without owning
# them: nothing here can create, change, or delete anything at Contabo.

data "contabo_image" "os" {
  id = var.contabo_image_id
}

data "contabo_instance" "existing" {
  id = var.contabo_instance_id
}

# Phase 4: keys and first-boot configuration.

# The public half of the admin's key, stored at Contabo as a "secret" so
# instances can reference it by ID.
resource "contabo_secret" "admin_ssh" {
  name  = "biasmarket-admin"
  type  = "ssh"
  value = trimspace(var.admin_ssh_public_key)
}

# Keys generated by Terraform. The private halves live in state (see the guide's
# "secrets in state" note), the public halves go to the server.
resource "tls_private_key" "deploy_rsync" {
  algorithm = "ED25519"
}

resource "tls_private_key" "deploy_dispatch" {
  algorithm = "ED25519"
}

resource "tls_private_key" "host" {
  algorithm = "ED25519"
}

locals {
  user_data = templatefile("${path.module}/cloud-init.yaml.tftpl", {
    host_private_key           = trimspace(tls_private_key.host.private_key_openssh)
    host_public_key            = trimspace(tls_private_key.host.public_key_openssh)
    deploy_rsync_public_key    = trimspace(tls_private_key.deploy_rsync.public_key_openssh)
    deploy_dispatch_public_key = trimspace(tls_private_key.deploy_dispatch.public_key_openssh)
  })
}

# Phase 3: the VPS bought by hand through the Contabo checkout, now adopted.
# Arguments mirror what the API reports for it today, so the first plan is empty.
resource "contabo_instance" "main" {
  product_id = "V153" # Cloud VPS 4 (2026)
  region     = "EU"
  image_id   = data.contabo_image.os.id
  period     = 1 # months, matches the 1-month term ordered

  # Both of these REINSTALL the server when they change (provider behavior).
  ssh_keys  = [tonumber(contabo_secret.admin_ssh.id)]
  user_data = local.user_data

  add_ons {
    id       = 1501
    quantity = 1
  }

  # The Contabo API does not return `period` or `region` when reading an
  # instance, so after an import they are null in state and would show as a
  # perpetual diff. They are kept above as documentation of intent (and for a
  # future create), and ignored afterwards.
  lifecycle {
    ignore_changes = [period, region]
  }
}
