#!/usr/bin/env node

// Creates a brand-new admin account from scratch — email in, autogenerated
// password printed out. Use this when the person doesn't have an account
// yet; if they already signed up normally, use promote-admin.ts instead.
// Usage: pnpm --filter api run admin:create <email> [name]

import { randomUUID, randomBytes } from 'node:crypto';
import { PrismaClient } from '@biasmarket/db';
import { PrismaPg } from '@prisma/adapter-pg';
import { hashPassword } from 'better-auth/crypto';

const email = process.argv[2];
const name = process.argv[3] ?? email?.split('@')[0];

if (!email) {
  console.error('Usage: node scripts/create-admin.ts <email> [name]');
  process.exit(1);
}

const adapter = new PrismaPg({ connectionString: process.env['DATABASE_URL'] });
const prisma = new PrismaClient({ adapter });

const existing = await prisma.user.findUnique({ where: { email } });

if (existing) {
  console.error(
    `${email} already exists — use "pnpm --filter api run admin:promote ${email}" instead.`,
  );
  await prisma.$disconnect();
  process.exit(1);
}

const password = randomBytes(18).toString('base64url');
const userId = randomUUID();
const now = new Date();

await prisma.user.create({
  data: {
    id: userId,
    name,
    email,
    emailVerified: true,
    role: 'admin',
    createdAt: now,
    updatedAt: now,
  },
});

await prisma.account.create({
  data: {
    id: randomUUID(),
    accountId: userId,
    providerId: 'credential',
    userId,
    password: await hashPassword(password),
    createdAt: now,
    updatedAt: now,
  },
});

console.log(`Created admin ${email}`);
console.log(`Password: ${password}`);
console.log('Save this now — it is not stored or shown again.');

await prisma.$disconnect();
