import { Test, TestingModule } from "@nestjs/testing";
import { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";

const mailerDevDir = join(__dirname, "..", ".mailer-dev");

async function waitForNewMailerFile(
  existingFiles: Set<string>,
  timeoutMs = 5000,
): Promise<string> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const current = readdirSync(mailerDevDir);
    const added = current.find((f) => !existingFiles.has(f));
    if (added) return join(mailerDevDir, added);
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error("Timed out waiting for verification email to be written");
}

// Validates real category responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const categorySchema = {
  ...openapi.components.schemas.CategoryResponseDto,
  components: openapi.components,
};

function assertMatchesSchema(
  value: unknown,
  schema: Record<string, unknown>,
  components: Record<string, unknown>,
  path = "$",
): void {
  const resolved = resolveSchema(schema, components);
  if (resolved.type === "object") {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      throw new Error(`${path}: expected object, got ${JSON.stringify(value)}`);
    }
    const properties = (resolved.properties ?? {}) as Record<string, unknown>;
    const required = (resolved.required ?? []) as string[];
    for (const key of required) {
      if (!(key in (value as Record<string, unknown>))) {
        throw new Error(`${path}: missing required property "${key}"`);
      }
    }
    for (
      const [key, propValue] of Object.entries(value as Record<string, unknown>)
    ) {
      const propSchema = properties[key];
      if (!propSchema) {
        throw new Error(`${path}.${key}: property not declared in schema`);
      }
      assertMatchesSchema(
        propValue,
        propSchema as Record<string, unknown>,
        components,
        `${path}.${key}`,
      );
    }
    return;
  }
  if (resolved.type === "array") {
    if (!Array.isArray(value)) {
      throw new Error(`${path}: expected array, got ${JSON.stringify(value)}`);
    }
    value.forEach((item, i) =>
      assertMatchesSchema(
        item,
        resolved.items as Record<string, unknown>,
        components,
        `${path}[${i}]`,
      )
    );
    return;
  }
  if (resolved.nullable && value === null) return;
  if (resolved.type === "string" && typeof value !== "string") {
    throw new Error(`${path}: expected string, got ${JSON.stringify(value)}`);
  }
  if (resolved.type === "number" && typeof value !== "number") {
    throw new Error(`${path}: expected number, got ${JSON.stringify(value)}`);
  }
  if (resolved.type === "boolean" && typeof value !== "boolean") {
    throw new Error(`${path}: expected boolean, got ${JSON.stringify(value)}`);
  }
}

function resolveSchema(
  schema: Record<string, unknown>,
  components: Record<string, unknown>,
): Record<string, unknown> {
  const ref = schema["$ref"] as string | undefined;
  if (!ref) return schema;
  const name = ref.replace("#/components/schemas/", "");
  const schemas = (components as { schemas: Record<string, unknown> }).schemas;
  return schemas[name] as Record<string, unknown>;
}

describe("categories (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let categoryId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `categories-e2e-${runId}@example.com`;
  const storeSlug = `categories-e2e-${runId}`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (categoryId) {
      await prisma.category.deleteMany({ where: { id: categoryId } });
    }
    if (storeId) {
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("GET /stores/:storeId/categories matches the generated openapi.json schema", async () => {
    const createRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/categories`)
      .set("Cookie", sessionCookie)
      .send({ name: "Photocards" })
      .expect(201);
    categoryId = createRes.body.id;
    assertMatchesSchema(createRes.body, categorySchema, openapi.components);
    expect(typeof createRes.body.createdAt).toBe("string");

    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/categories`)
      .set("Cookie", sessionCookie)
      .expect(200);

    expect(Array.isArray(res.body)).toBe(true);
    const created = res.body.find((c: { id: string }) => c.id === categoryId);
    expect(created).toBeDefined();

    for (const category of res.body) {
      assertMatchesSchema(category, categorySchema, openapi.components);
    }
  });
});
