import { Test, TestingModule } from "@nestjs/testing";
import { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates a real collections response against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json) — an ongoing
// contract check, not the one-time manual read the plan doc's Phase 1
// checkpoint describes. Run `pnpm --filter api generate:openapi` before this
// test if openapi.json is missing or stale relative to the DTOs.
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const collectionSchema =
  openapi.components.schemas.CollectionWithProductsResponseDto;

describe("collections (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let collectionId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `collections-e2e-${runId}@example.com`;
  const storeSlug = `collections-e2e-${runId}`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    // `requireEmailVerification: true` (auth.config.ts) means sign-up alone
    // doesn't issue a session — verify via the real link first, same as a
    // real user would, then sign in normally to get a real session cookie.
    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (collectionId) {
      await prisma.collectionProduct.deleteMany({ where: { collectionId } });
      await prisma.collection.deleteMany({ where: { id: collectionId } });
    }
    if (storeId) {
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("GET /stores/:storeId/collections matches the generated openapi.json schema", async () => {
    const createRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/collections`)
      .set("Cookie", sessionCookie)
      .send({ name: "E2E Collection" })
      .expect(201);
    collectionId = createRes.body.id;

    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/collections`)
      .set("Cookie", sessionCookie)
      .expect(200);

    expect(Array.isArray(res.body)).toBe(true);
    const created = res.body.find(
      (c: { id: string }) => c.id === collectionId,
    );
    expect(created).toBeDefined();

    for (const collection of res.body) {
      assertMatchesSchema(collection, collectionSchema, openapi.components);
    }
  });
});
