import { Test, TestingModule } from "@nestjs/testing";
import { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";

const mailerDevDir = join(__dirname, "..", ".mailer-dev");

async function waitForNewMailerFile(
  existingFiles: Set<string>,
  timeoutMs = 5000,
): Promise<string> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const current = readdirSync(mailerDevDir);
    const added = current.find((f) => !existingFiles.has(f));
    if (added) return join(mailerDevDir, added);
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error("Timed out waiting for verification email to be written");
}

// Validates real contact-inquiry responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const inquirySchema = {
  ...openapi.components.schemas.InquiryResponseDto,
  components: openapi.components,
};

function assertMatchesSchema(
  value: unknown,
  schema: Record<string, unknown>,
  components: Record<string, unknown>,
  path = "$",
): void {
  const resolved = resolveSchema(schema, components);
  if (resolved.type === "object") {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      throw new Error(`${path}: expected object, got ${JSON.stringify(value)}`);
    }
    const properties = (resolved.properties ?? {}) as Record<string, unknown>;
    const required = (resolved.required ?? []) as string[];
    for (const key of required) {
      if (!(key in (value as Record<string, unknown>))) {
        throw new Error(`${path}: missing required property "${key}"`);
      }
    }
    for (
      const [key, propValue] of Object.entries(value as Record<string, unknown>)
    ) {
      const propSchema = properties[key];
      if (!propSchema) {
        throw new Error(`${path}.${key}: property not declared in schema`);
      }
      assertMatchesSchema(
        propValue,
        propSchema as Record<string, unknown>,
        components,
        `${path}.${key}`,
      );
    }
    return;
  }
  if (resolved.type === "array") {
    if (!Array.isArray(value)) {
      throw new Error(`${path}: expected array, got ${JSON.stringify(value)}`);
    }
    value.forEach((item, i) =>
      assertMatchesSchema(
        item,
        resolved.items as Record<string, unknown>,
        components,
        `${path}[${i}]`,
      )
    );
    return;
  }
  if (resolved.nullable && value === null) return;
  if (resolved.type === "string" && typeof value !== "string") {
    throw new Error(`${path}: expected string, got ${JSON.stringify(value)}`);
  }
  if (resolved.type === "number" && typeof value !== "number") {
    throw new Error(`${path}: expected number, got ${JSON.stringify(value)}`);
  }
  if (resolved.type === "boolean" && typeof value !== "boolean") {
    throw new Error(`${path}: expected boolean, got ${JSON.stringify(value)}`);
  }
}

function resolveSchema(
  schema: Record<string, unknown>,
  components: Record<string, unknown>,
): Record<string, unknown> {
  const ref = schema["$ref"] as string | undefined;
  if (!ref) return schema;
  const name = ref.replace("#/components/schemas/", "");
  const schemas = (components as { schemas: Record<string, unknown> }).schemas;
  return schemas[name] as Record<string, unknown>;
}

describe("contact (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let adminSessionCookie: string;
  let adminUserId: string;
  let inquiryId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const adminEmail = `contact-e2e-admin-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email: adminEmail, password, name: "E2E Admin" })
      .expect(200);
    adminUserId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    // No public "become admin" flow exists — seeding the role directly via
    // Prisma is the only way to exercise the admin-guarded endpoints below.
    await prisma.user.update({
      where: { id: adminUserId },
      data: { role: "admin" },
    });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email: adminEmail, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    adminSessionCookie = raw.split(";")[0]!;
  });

  afterAll(async () => {
    if (inquiryId) {
      await prisma.contactInquiry.deleteMany({ where: { id: inquiryId } });
    }
    if (adminUserId) {
      await prisma.user.deleteMany({ where: { id: adminUserId } });
    }
    await app.close();
  });

  it("POST /contact, GET /contact, PATCH /contact/:id/review match the generated openapi.json schema", async () => {
    const createRes = await request(app.getHttpServer())
      .post("/contact")
      .send({
        name: "E2E Contact",
        email: `e2e-contact-${runId}@example.com`,
        message: "Testing the generated client migration.",
      })
      .expect(201);
    inquiryId = createRes.body.id;
    assertMatchesSchema(createRes.body, inquirySchema, openapi.components);
    expect(createRes.body.status).toBe("NEW");

    const listRes = await request(app.getHttpServer())
      .get("/contact")
      .set("Cookie", adminSessionCookie)
      .expect(200);
    expect(Array.isArray(listRes.body)).toBe(true);
    const created = listRes.body.find(
      (i: { id: string }) => i.id === inquiryId,
    );
    expect(created).toBeDefined();
    for (const inquiry of listRes.body) {
      assertMatchesSchema(inquiry, inquirySchema, openapi.components);
    }

    const reviewRes = await request(app.getHttpServer())
      .patch(`/contact/${inquiryId}/review`)
      .set("Cookie", adminSessionCookie)
      .expect(200);
    assertMatchesSchema(reviewRes.body, inquirySchema, openapi.components);
    expect(reviewRes.body.status).toBe("REVIEWED");
  });
});
