import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real Customers responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
// `CustomerDetailResponseDto.orders` reuses `Order`'s own `OrderResponseDto`
// (see customers-response.dto.ts's comment) — this spec exercises a real
// paid order so the full reused shape (items/payments/paidAmount/etc.) gets a
// real HTTP round trip, not just a schema eyeball on an empty order.
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const listItemSchema = openapi.components.schemas.CustomerListItemResponseDto;
const detailSchema = openapi.components.schemas.CustomerDetailResponseDto;

describe("customers (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sellerSessionCookie: string;
  let sellerUserId: string;
  let storeId: string;
  let storeSlug: string;
  let productId: string;
  let customerId: string;
  let orderId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const sellerEmail = `customers-e2e-seller-${runId}@example.com`;
  const customerEmail = `customers-e2e-customer-${runId}@example.com`;
  const customerPhone = "+51977777777";

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email: sellerEmail, password, name: "E2E Seller" })
      .expect(200);
    sellerUserId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(
      existingMailerFiles,
      sellerEmail,
    );
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email: sellerEmail, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sellerSessionCookie = raw.split(";")[0]!;

    storeSlug = `customers-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sellerSessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set("Cookie", sellerSessionCookie)
      .send({ name: "E2E Product", price: 20, currency: "PEN", stock: 100 })
      .expect(201);
    productId = productRes.body.id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);

    const checkoutRes = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .send({
        deliveryMethodType: "PICKUP",
        customerPhone,
        customerEmail,
        customerName: "E2E Customer",
        items: [{ productId, quantity: 1 }],
      })
      .expect(201);
    orderId = checkoutRes.body.order.id as string;

    const customer = await prisma.customer.findUniqueOrThrow({
      where: { storeId_phone: { storeId, phone: customerPhone } },
    });
    customerId = customer.id;

    await request(app.getHttpServer())
      .post(`/stores/${storeId}/orders/${orderId}/payments`)
      .set("Cookie", sellerSessionCookie)
      .field("amount", "20")
      .field("method", "YAPE")
      .expect(201);
  });

  afterAll(async () => {
    if (orderId) {
      await prisma.orderPayment.deleteMany({ where: { orderId } });
      await prisma.orderItem.deleteMany({ where: { orderId } });
      await prisma.order.deleteMany({ where: { id: orderId } });
    }
    if (customerId) {
      await prisma.customer.deleteMany({ where: { id: customerId } });
    }
    if (productId) {
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (sellerUserId) {
      await prisma.user.deleteMany({ where: { id: sellerUserId } });
    }
    await app.close();
  });

  it("GET /customers matches CustomerListItemResponseDto", async () => {
    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/customers`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);
    expect(Array.isArray(res.body)).toBe(true);
    const listed = res.body.find((c: { id: string }) => c.id === customerId);
    expect(listed).toBeDefined();
    expect(listed.orderCount).toBe(1);
    expect(listed.lifetimeSpend).toBe(20);
    for (const item of res.body) {
      assertMatchesSchema(item, listItemSchema, openapi.components);
    }
  });

  it("GET /customers/:customerId matches CustomerDetailResponseDto (reused OrderResponseDto)", async () => {
    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/customers/${customerId}`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);
    assertMatchesSchema(res.body, detailSchema, openapi.components);
    expect(res.body.customer.id).toBe(customerId);
    expect(res.body.orders).toHaveLength(1);
    const order = res.body.orders[0];
    expect(order.id).toBe(orderId);
    expect(typeof order.totalAmount).toBe("string");
    expect(order.paidAmount).toBe(20);
    expect(order.pendingAmount).toBe(0);
    expect(order.paymentStatus).toBe("VERIFIED");
    expect(order.items).toHaveLength(1);
    expect(order.payments).toHaveLength(1);
    // Order.findOne (Batch 4) reuses this exact shape too — confirm they
    // stay identical for orders belonging to a real customer.
    const orderFindOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);
    expect(order.paidAmount).toBe(orderFindOneRes.body.paidAmount);
    expect(order.pendingAmount).toBe(orderFindOneRes.body.pendingAmount);
  });
});
