import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real CustomerAccount/CustomerAuth responses against the schema
// generated by `pnpm --filter api generate:openapi` (apps/api/openapi.json).
// Combined into one spec (matching orders.e2e-spec.ts's Order+Checkout
// precedent) because both tags share the same underlying customer lifecycle:
// a guest checkout creates the `Customer` row and sends the "confirm" email
// that `CustomerAccountController.confirm` and `CustomerAuthController
// .register` both consume.
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const confirmSchema = openapi.components.schemas.ConfirmAccountResponseDto;
const okSchema = openapi.components.schemas.OkResponseDto;
const profileSchema = openapi.components.schemas.CustomerProfileResponseDto;
const updateProfileSchema =
  openapi.components.schemas.UpdateCustomerProfileResponseDto;

describe("customer account + customer auth (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sellerSessionCookie: string;
  let sellerUserId: string;
  let storeId: string;
  let storeSlug: string;
  let productId: string;
  let productVariantId: string;
  let customerId: string | undefined;
  let orderId: string | undefined;
  let customerSessionCookie: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const sellerEmail = `caa-e2e-seller-${runId}@example.com`;
  const customerEmail = `caa-e2e-customer-${runId}@example.com`;
  const customerPhone = "+51966666666";
  const password = "correcthorsebatterystaple";

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email: sellerEmail, password, name: "E2E Seller" })
      .expect(200);
    sellerUserId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(
      existingMailerFiles,
      sellerEmail,
    );
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email: sellerEmail, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sellerSessionCookie = raw.split(";")[0]!;

    storeSlug = `caa-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sellerSessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set("Cookie", sellerSessionCookie)
      .send({ name: "E2E Product", price: 10, currency: "PEN", stock: 100 })
      .expect(201);
    productId = productRes.body.id;
    // `stock` at the top level auto-creates a "Default" ProductVariant —
    // checkout must name it explicitly (see orders.e2e-spec.ts's identical
    // comment on the same pattern).
    productVariantId = productRes.body.variants[0].id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);
  });

  afterAll(async () => {
    if (orderId) {
      await prisma.orderItem.deleteMany({ where: { orderId } });
      await prisma.order.deleteMany({ where: { id: orderId } });
    }
    if (customerId) {
      await prisma.customer.deleteMany({ where: { id: customerId } });
    }
    if (productId) {
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (sellerUserId) {
      await prisma.user.deleteMany({ where: { id: sellerUserId } });
    }
    await app.close();
  });

  it(
    "checkout with customerEmail -> confirm -> register -> login -> me -> " +
      "updateMe -> changePassword -> logout -> forgotPassword",
    async () => {
      const existingMailerFiles = new Set(readdirSync(mailerDevDir));

      const checkoutRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/checkout`)
        .send({
          deliveryMethodType: "PICKUP",
          customerPhone,
          customerEmail,
          customerName: "E2E Customer",
          items: [{ productId, variantId: productVariantId, quantity: 1 }],
        })
        .expect(201);
      orderId = checkoutRes.body.order.id as string;

      const customer = await prisma.customer.findUniqueOrThrow({
        where: { storeId_phone: { storeId, phone: customerPhone } },
      });
      customerId = customer.id;
      expect(customer.emailVerified).toBe(false);

      const mailerFile = await waitForNewMailerFile(
        existingMailerFiles,
        customerEmail,
      );
      const html = readFileSync(mailerFile, "utf-8");
      const tokenMatch = html.match(/token=([^&"]+)/);
      if (!tokenMatch) {
        throw new Error("confirm-account link not found in email");
      }
      const token = tokenMatch[1]!;

      // CustomerAccount.confirm — marks emailVerified, purpose "confirm".
      const confirmRes = await request(app.getHttpServer())
        .get(`/stores/${storeSlug}/account/confirm?token=${token}`)
        .expect(200);
      assertMatchesSchema(confirmRes.body, confirmSchema, openapi.components);
      expect(confirmRes.body.purpose).toBe("confirm");
      expect(confirmRes.body.customer.hasPassword).toBe(false);
      expect(Array.isArray(confirmRes.body.orders)).toBe(true);
      const confirmedOrder = confirmRes.body.orders.find(
        (o: { id: string }) => o.id === orderId,
      );
      expect(confirmedOrder).toBeDefined();
      expect(typeof confirmedOrder.totalAmount).toBe("string");

      // CustomerAuth.register — the "confirm"-purpose token is replayable
      // within its TTL (stateless HMAC, see CustomerAuthService.register's
      // comment), so the same token works here too.
      const registerRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/register`)
        .set("Origin", "http://localhost:3001")
        .send({ token, password })
        .expect(201);
      assertMatchesSchema(registerRes.body, okSchema, openapi.components);
      expect(registerRes.body.ok).toBe(true);

      // CustomerAuth.login
      const loginRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/login`)
        .set("Origin", "http://localhost:3001")
        .send({ phone: customerPhone, password })
        .expect(201);
      assertMatchesSchema(loginRes.body, okSchema, openapi.components);
      const setCookie = loginRes.headers["set-cookie"] as unknown as string[];
      const raw = setCookie?.find((c) => c.includes("bm_customer_session"));
      if (!raw) throw new Error("login did not return a session cookie");
      customerSessionCookie = raw.split(";")[0]!;

      // CustomerAuth.me
      const meRes = await request(app.getHttpServer())
        .get(`/stores/${storeSlug}/account/me`)
        .set("Cookie", customerSessionCookie)
        .expect(200);
      assertMatchesSchema(meRes.body, profileSchema, openapi.components);
      expect(meRes.body.customer.emailVerified).toBe(true);
      expect(meRes.body.orders).toHaveLength(1);
      expect(meRes.body.orders[0].id).toBe(orderId);
      expect(typeof meRes.body.orders[0].totalAmount).toBe("string");

      // CustomerAuth.updateMe
      const updateRes = await request(app.getHttpServer())
        .patch(`/stores/${storeSlug}/account/me`)
        .set("Cookie", customerSessionCookie)
        .set("Origin", "http://localhost:3001")
        .send({ name: "E2E Customer Updated" })
        .expect(200);
      assertMatchesSchema(
        updateRes.body,
        updateProfileSchema,
        openapi.components,
      );
      expect(updateRes.body.name).toBe("E2E Customer Updated");

      // CustomerAuth.changePassword — the real point of Batch 5's spec-bug
      // fix: this route has no `@Param("slug")` in the method signature, only
      // `@ApiParam`, so this call also confirms the route still resolves
      // `:slug` from the path at runtime post-fix.
      const newPassword = "correcthorsebatterystaple2";
      const changePasswordRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/change-password`)
        .set("Cookie", customerSessionCookie)
        .set("Origin", "http://localhost:3001")
        .send({ currentPassword: password, newPassword })
        .expect(201);
      assertMatchesSchema(
        changePasswordRes.body,
        okSchema,
        openapi.components,
      );

      // CustomerAuth.logout — same no-`@Param("slug")` shape as
      // changePassword.
      const logoutRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/logout`)
        .set("Cookie", customerSessionCookie)
        .expect(201);
      assertMatchesSchema(logoutRes.body, okSchema, openapi.components);

      // CustomerAuth.forgotPassword
      const forgotRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/forgot-password`)
        .set("Origin", "http://localhost:3001")
        .send({ phone: customerPhone })
        .expect(201);
      assertMatchesSchema(forgotRes.body, okSchema, openapi.components);

      // Regression coverage for the phone-normalization bug (see
      // docs/plans/2026-08-06-buyer-phone-normalization-fix.md): a buyer
      // types their phone one way at checkout ("+51966666666", the constant
      // above) and a different-but-equivalent way at login/forgot-password
      // ("966666666", no dial code) — both must resolve to the same
      // Customer row. Uses `newPassword` since changePassword ran above.
      const differentlyFormattedPhone = customerPhone.replace(/^\+51/, "");

      const loginWithDifferentFormatRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/login`)
        .set("Origin", "http://localhost:3001")
        .send({ phone: differentlyFormattedPhone, password: newPassword })
        .expect(201);
      assertMatchesSchema(
        loginWithDifferentFormatRes.body,
        okSchema,
        openapi.components,
      );

      // Snapshot the mailer dir here so the reset-email assertion below only
      // sees the email written by this specific forgotPassword call — the
      // earlier confirm/register emails to the same customer address are
      // excluded.
      const mailerFilesBeforeForgot = new Set(readdirSync(mailerDevDir));

      const forgotWithDifferentFormatRes = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/account/forgot-password`)
        .set("Origin", "http://localhost:3001")
        .send({ phone: differentlyFormattedPhone })
        .expect(201);
      assertMatchesSchema(
        forgotWithDifferentFormatRes.body,
        okSchema,
        openapi.components,
      );

      // Asserting the reset *side effect*, not just the 201: the
      // differently-formatted phone must still resolve to the same Customer
      // and produce a reset email addressed to them.
      const resetMailerFile = await waitForNewMailerFile(
        mailerFilesBeforeForgot,
        customerEmail,
      );
      const resetHtml = readFileSync(resetMailerFile, "utf-8");
      expect(resetHtml).toMatch(/account\/confirm\?token=/);
    },
  );
});
