import { Test, TestingModule } from "@nestjs/testing";
import { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real delivery-method-config responses (private CRUD + public
// read-only sibling) against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const deliveryMethodSchema =
  openapi.components.schemas.DeliveryMethodConfigResponseDto;

describe("delivery-config (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let storeSlug: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `delivery-config-e2e-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    storeSlug = `delivery-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (storeId) {
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("findAll/upsert/remove/public findEnabled match DeliveryMethodConfigResponseDto", async () => {
    // Store.create auto-creates a PICKUP row (see StoresService.create) —
    // findAll should already return it.
    const listRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/delivery-methods`)
      .set("Cookie", sessionCookie)
      .expect(200);
    expect(Array.isArray(listRes.body)).toBe(true);
    expect(listRes.body.some((m: { type: string }) => m.type === "PICKUP"))
      .toBe(true);
    for (const method of listRes.body) {
      assertMatchesSchema(method, deliveryMethodSchema, openapi.components);
    }

    const upsertRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/delivery-methods`)
      .set("Cookie", sessionCookie)
      .send({ type: "COURIER", enabled: true, details: { fee: 10 } })
      .expect(201);
    assertMatchesSchema(
      upsertRes.body,
      deliveryMethodSchema,
      openapi.components,
    );
    expect(upsertRes.body.type).toBe("COURIER");
    expect(upsertRes.body.details).toEqual({ fee: 10 });

    const publicRes = await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/public/delivery-methods`)
      .expect(200);
    expect(Array.isArray(publicRes.body)).toBe(true);
    expect(publicRes.body.length).toBeGreaterThanOrEqual(2);
    for (const method of publicRes.body) {
      assertMatchesSchema(method, deliveryMethodSchema, openapi.components);
    }

    const removeRes = await request(app.getHttpServer())
      .delete(`/stores/${storeId}/delivery-methods/COURIER`)
      .set("Cookie", sessionCookie)
      .expect(200);
    assertMatchesSchema(
      removeRes.body,
      deliveryMethodSchema,
      openapi.components,
    );
    expect(removeRes.body.type).toBe("COURIER");
  });
});
