import { Test, type TestingModule } from '@nestjs/testing';
import type { INestApplication } from '@nestjs/common';
import { PrismaService } from '../src/prisma/prisma.service.js';
import { StorageService } from '../src/storage/storage.service.js';
import request from 'supertest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { AppModule } from './../src/app.module.js';
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from './schema-assert.js';

// Validates real Order/Checkout responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json) — the second
// and last money-bearing module after Products (see
// docs/plans/2026-08-05-orval-rollout-batch-4-order-checkout-plan.md).
// Exercises all three real Order response shapes (OrderResponseDto from
// findAll, OrderDetailResponseDto from findOne/addPayment,
// OrderStatusResponseDto from review/advance/cancel) plus Checkout's own,
// narrower CheckoutResultResponseDto — across four separate orders so each
// lifecycle path (full payment via addPayment, partial payment + explicit
// review approve, review reject, cancel) gets a real HTTP round trip, not
// just a schema eyeball.
const openapiPath = join(__dirname, '..', 'openapi.json');
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, 'utf-8');
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const orderSchema = openapi.components.schemas.OrderResponseDto;
const orderDetailSchema = openapi.components.schemas.OrderDetailResponseDto;
const orderStatusSchema = openapi.components.schemas.OrderStatusResponseDto;
const checkoutResultSchema =
  openapi.components.schemas.CheckoutResultResponseDto;

describe('orders + checkout (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let storage: StorageService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let storeSlug: string;
  let productId: string;
  let productVariantId: string;
  const orderIds: string[] = [];
  let uploadedPaymentImageUrl: string | undefined;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `orders-e2e-${runId}@example.com`;
  const courierName = 'Olva';
  const courierModality = 'HOME';
  let checkoutIpCounter = 0;

  function nextCheckoutIp(): string {
    checkoutIpCounter += 1;
    return `198.51.100.${checkoutIpCounter}`;
  }

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    // Keep each independent attempt below the production checkout limit while
    // preserving the real throttler in this contract suite.
    app.getHttpAdapter().getInstance().set('trust proxy', true);
    await app.init();
    prisma = moduleFixture.get(PrismaService);
    storage = moduleFixture.get(StorageService);

    const password = 'correcthorsebatterystaple';
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post('/api/auth/sign-up/email')
      .send({ email, password, name: 'E2E Seller' })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, 'utf-8');
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error('verification link not found in email');
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post('/api/auth/sign-in/email')
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers['set-cookie'] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes('session_token'));
    if (!raw) throw new Error('sign-in did not return a session cookie');
    sessionCookie = raw.split(';')[0]!;

    storeSlug = `orders-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post('/stores')
      .set('Cookie', sessionCookie)
      .send({
        name: 'E2E Store',
        slug: storeSlug,
        whatsappNumber: '+51900000000',
      })
      .expect(201);
    storeId = storeRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set('Cookie', sessionCookie)
      .send({ name: 'E2E Product', price: 25, currency: 'PEN', stock: 100 })
      .expect(201);
    productId = productRes.body.id;
    // `stock` at the top level makes products.service auto-create a single
    // "Default" ProductVariant — CreateOrderUseCase then requires items for
    // this product to name it explicitly (see
    // create-order.usecase.ts's "Debes seleccionar una variante" guard).
    productVariantId = productRes.body.variants[0].id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set('Cookie', sessionCookie)
      .expect(200);

    // Only PICKUP is auto-created on store creation (stores.service.ts) —
    // COURIER checkout tests below need it explicitly enabled.
    await request(app.getHttpServer())
      .post(`/stores/${storeId}/delivery-methods`)
      .set('Cookie', sessionCookie)
      .send({ type: 'COURIER', enabled: true, details: { estimatedCost: 10 } })
      .expect(201);
    await request(app.getHttpServer())
      .post(`/stores/${storeId}/couriers`)
      .set('Cookie', sessionCookie)
      .send({
        name: courierName,
        modalities: [{ modality: courierModality, price: 10 }],
      })
      .expect(201);
  });

  afterAll(async () => {
    if (uploadedPaymentImageUrl) {
      await storage.deleteImage(uploadedPaymentImageUrl);
    }
    if (orderIds.length > 0) {
      await prisma.orderPayment.deleteMany({
        where: { orderId: { in: orderIds } },
      });
      await prisma.orderItem.deleteMany({
        where: { orderId: { in: orderIds } },
      });
      await prisma.order.deleteMany({ where: { id: { in: orderIds } } });
    }
    if (productId) {
      // A failed assertion or a checkout that completed before the test saw
      // its response can leave an order outside `orderIds`. Clear every
      // dependent row for this isolated store before deleting its products;
      // OrderItem.productId is RESTRICT by design.
      await prisma.orderPayment.deleteMany({ where: { storeId } });
      await prisma.orderItem.deleteMany({ where: { storeId } });
      await prisma.order.deleteMany({ where: { storeId } });
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (storeId) {
      // The suite creates additional precision/race products in individual
      // tests. They must be removed as well before the store FK is deleted.
      await prisma.productVariant.deleteMany({ where: { storeId } });
      await prisma.product.deleteMany({ where: { storeId } });
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.courierConfig.deleteMany({
        where: { courier: { storeId } },
      });
      await prisma.courier.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  async function checkout(
    customerPhone: string,
    options?: {
      paymentMethod?: string;
      proof?: Buffer;
      proofName?: string;
    },
  ): Promise<string> {
    let req = request(app.getHttpServer()).post(
      `/stores/${storeSlug}/checkout`,
    );
    req = req.set('X-Forwarded-For', nextCheckoutIp());
    req = req.field('deliveryMethodType', 'PICKUP');
    req = req.field('customerPhone', customerPhone);
    req = req.field(
      'items',
      JSON.stringify([{ productId, variantId: productVariantId, quantity: 1 }]),
    );
    if (options?.paymentMethod) {
      req = req.field('paymentMethod', options.paymentMethod);
    }
    if (options?.proof) {
      req = req.attach('file', options.proof, options.proofName ?? 'proof.png');
    }
    const res = await req.expect(201);
    assertMatchesSchema(res.body, checkoutResultSchema, openapi.components);
    expect(typeof res.body.order.totalAmount).toBe('string');
    const orderId = res.body.order.id as string;
    orderIds.push(orderId);
    return orderId;
  }

  // Minimal valid PDF — `%PDF-` magic prefix is all the backend's
  // proof-format check looks for, and this is the smallest honest buffer
  // that carries it.
  const pdfBuffer = Buffer.from(
    '%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF',
    'latin1',
  );

  // 1x1 PNG, smallest valid file that passes the controller's magic-byte check.
  const pngBuffer = Buffer.from(
    '89504e470d0a1a0a0000000d4948445200000001000000010802000000907753de0000000c4944415478da6360606060000000050001a5f645400000000049454e44ae426082',
    'hex',
  );

  it('checkout -> findAll/findOne -> addPayment (full) -> advance fulfillment', async () => {
    const orderId = await checkout('+51911111111');

    const listRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders`)
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(Array.isArray(listRes.body)).toBe(true);
    const listed = listRes.body.find((o: { id: string }) => o.id === orderId);
    expect(listed).toBeDefined();
    expect(typeof listed.totalAmount).toBe('string');
    expect(typeof listed.paidAmount).toBe('number');
    for (const order of listRes.body) {
      assertMatchesSchema(order, orderSchema, openapi.components);
    }

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    assertMatchesSchema(findOneRes.body, orderDetailSchema, openapi.components);
    expect(findOneRes.body.paymentStatus).toBe('PENDING_PAYMENT');
    const requiredAmount = findOneRes.body.requiredAmount as string;

    const paymentRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/orders/${orderId}/payments`)
      .set('Cookie', sessionCookie)
      .field('amount', requiredAmount)
      .field('method', 'YAPE')
      .attach('file', pngBuffer, 'proof.png')
      .expect(201);
    assertMatchesSchema(paymentRes.body, orderDetailSchema, openapi.components);
    expect(paymentRes.body.paymentStatus).toBe('VERIFIED');
    expect(paymentRes.body.paidAmount).toBe(Number(requiredAmount));
    expect(paymentRes.body.payments).toHaveLength(1);
    expect(typeof paymentRes.body.payments[0].imageUrl).toBe('string');
    uploadedPaymentImageUrl = paymentRes.body.payments[0].imageUrl;

    const advanceRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/orders/${orderId}/fulfillment`)
      .set('Cookie', sessionCookie)
      .send({ status: 'IN_TRANSIT' })
      .expect(200);
    assertMatchesSchema(advanceRes.body, orderStatusSchema, openapi.components);
    expect(advanceRes.body.fulfillmentStatus).toBe('IN_TRANSIT');
  });

  it('checkout -> partial addPayment -> explicit review approve matches OrderStatusResponseDto', async () => {
    const orderId = await checkout('+51922222222');

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    const requiredAmount = Number(findOneRes.body.requiredAmount);

    await request(app.getHttpServer())
      .post(`/stores/${storeId}/orders/${orderId}/payments`)
      .set('Cookie', sessionCookie)
      .field('amount', String(requiredAmount / 2))
      .field('method', 'TRANSFER')
      .expect(201)
      .expect((res) => {
        if (res.body.paymentStatus !== 'PARTIALLY_PAID') {
          throw new Error(
            `expected PARTIALLY_PAID, got ${res.body.paymentStatus}`,
          );
        }
      });

    const reviewRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/orders/${orderId}/review`)
      .set('Cookie', sessionCookie)
      .send({ decision: 'approve' })
      .expect(200);
    assertMatchesSchema(reviewRes.body, orderStatusSchema, openapi.components);
    expect(reviewRes.body.paymentStatus).toBe('VERIFIED');
  });

  it('checkout -> review reject matches OrderStatusResponseDto', async () => {
    const orderId = await checkout('+51933333333');

    const reviewRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/orders/${orderId}/review`)
      .set('Cookie', sessionCookie)
      .send({ decision: 'reject', reason: 'E2E rejection' })
      .expect(200);
    assertMatchesSchema(reviewRes.body, orderStatusSchema, openapi.components);
    expect(reviewRes.body.paymentStatus).toBe('REJECTED');
  });

  // Regression coverage for the order-status-without-payment bug (see
  // docs/plans/2026-08-06-order-status-buyer-login-pickup-checkout-fixes-plan.md
  // §1): approving straight from PENDING_PAYMENT with zero payments registered
  // must 400, not silently produce a VERIFIED order with paidAmount 0.
  // Does its own checkout POST (rather than the shared `checkout()` helper)
  // because it needs the raw order id to assert the 400 on the follow-up
  // review call.
  it('checkout -> review approve with zero payments registered 400s', async () => {
    const checkoutRes = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'PICKUP')
      .field('customerPhone', '+51966666666')
      .field(
        'items',
        JSON.stringify([
          { productId, variantId: productVariantId, quantity: 1 },
        ]),
      )
      .expect(201);
    const orderId = checkoutRes.body.order.id as string;
    orderIds.push(orderId);

    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/orders/${orderId}/review`)
      .set('Cookie', sessionCookie)
      .send({ decision: 'approve' })
      .expect(400);

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(findOneRes.body.paymentStatus).toBe('PENDING_PAYMENT');
  });

  it('checkout -> cancel matches OrderStatusResponseDto', async () => {
    const orderId = await checkout('+51944444444');

    const cancelRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/orders/${orderId}/cancel`)
      .set('Cookie', sessionCookie)
      .send({ resolution: 'RETAINED', reason: 'E2E cancel' })
      .expect(200);
    assertMatchesSchema(cancelRes.body, orderStatusSchema, openapi.components);
    expect(cancelRes.body.status).toBe('CANCELLED');
    expect(cancelRes.body.paymentStatus).toBe('CANCELLED');
  });

  // Coverage for docs/plans/2026-08-08-buyer-shipping-addresses-plan.md:
  // COURIER checkout requires an inline shippingAddress (no addressId
  // picker — see the plan's "Important correction" section).
  it('checkout COURIER without shippingAddress 400s', async () => {
    await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'COURIER')
      .field('courierName', courierName)
      .field('courierModality', courierModality)
      .field('customerPhone', '+51955555511')
      .field(
        'items',
        JSON.stringify([
          { productId, variantId: productVariantId, quantity: 1 },
        ]),
      )
      .expect(400);
  });

  it("checkout COURIER snapshots shippingAddress into the order's deliveryDetails", async () => {
    const shippingAddress = {
      recipientName: 'Jane Doe',
      phone: '+51955555522',
      line1: 'Av. Principal 123',
      city: 'Lima',
      region: 'Lima',
      reference: 'Frente al parque',
    };
    const checkoutRes = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'COURIER')
      .field('courierName', courierName)
      .field('courierModality', courierModality)
      .field('customerPhone', '+51955555522')
      .field(
        'items',
        JSON.stringify([
          { productId, variantId: productVariantId, quantity: 1 },
        ]),
      )
      .field('shippingAddress', JSON.stringify(shippingAddress))
      .expect(201);
    assertMatchesSchema(
      checkoutRes.body,
      checkoutResultSchema,
      openapi.components,
    );
    const orderId = checkoutRes.body.order.id as string;
    orderIds.push(orderId);
    expect(checkoutRes.body.order.deliveryDetails).toMatchObject({
      shippingAddress,
    });
  });

  // #120 — full / partial payment. CreateOrderUseCase only honors
  // `paymentType: 'PARTIAL'` for an enabled, non-CASH method whose config
  // sets `depositPercent < 100`; anything else is a 400
  // (create-order.usecase.ts). requiredAmount is
  // `finalAmount.times(pct).div(100)` rounded to 2 decimals, and finalAmount
  // already includes the delivery cost.
  describe('#120 partial payment', () => {
    async function upsertPaymentMethod(body: Record<string, unknown>) {
      await request(app.getHttpServer())
        .post(`/stores/${storeId}/payment-methods`)
        .set('Cookie', sessionCookie)
        .send(body)
        .expect(201);
    }

    function partialCheckout(
      phone: string,
      fields: Record<string, string>,
      proof?: Buffer,
    ) {
      let req = request(app.getHttpServer())
        .post(`/stores/${storeSlug}/checkout`)
        .set('X-Forwarded-For', nextCheckoutIp())
        .field('deliveryMethodType', 'PICKUP')
        .field('customerPhone', phone)
        .field(
          'items',
          JSON.stringify([
            { productId, variantId: productVariantId, quantity: 1 },
          ]),
        )
        .field('paymentType', 'PARTIAL');
      for (const [k, v] of Object.entries(fields)) req = req.field(k, v);
      if (proof) req = req.attach('file', proof, 'proof.png');
      return req;
    }

    it('rejects PARTIAL for a CASH method', async () => {
      await upsertPaymentMethod({ method: 'CASH', enabled: true });
      await partialCheckout('+51970000001', { paymentMethod: 'CASH' }).expect(
        400,
      );
    });

    it('rejects PARTIAL when depositPercent is 100', async () => {
      await upsertPaymentMethod({
        method: 'TRANSFER',
        enabled: true,
        details: {
          bankName: 'BCP',
          accountNumber: '111',
          accountHolder: 'E2E',
        },
        depositPercent: 100,
      });
      await partialCheckout(
        '+51970000002',
        { paymentMethod: 'TRANSFER' },
        pngBuffer,
      ).expect(400);
    });

    it('prices requiredAmount at round(subtotal * pct / 100, 2) over PICKUP', async () => {
      await upsertPaymentMethod({
        method: 'TRANSFER',
        enabled: true,
        details: {
          bankName: 'BCP',
          accountNumber: '222',
          accountHolder: 'E2E',
        },
        depositPercent: 20,
      });
      const res = await partialCheckout(
        '+51970000003',
        { paymentMethod: 'TRANSFER' },
        pngBuffer,
      ).expect(201);
      const orderId = res.body.order.id as string;
      orderIds.push(orderId);
      // product price 25, qty 1, no delivery cost on PICKUP.
      expect(Number(res.body.order.totalAmount)).toBe(25);
      expect(Number(res.body.order.requiredAmount)).toBe(5);
    });

    it('includes the courier delivery cost in the deposit base', async () => {
      await upsertPaymentMethod({
        method: 'TRANSFER',
        enabled: true,
        details: {
          bankName: 'BCP',
          accountNumber: '333',
          accountHolder: 'E2E',
        },
        depositPercent: 20,
      });
      const res = await request(app.getHttpServer())
        .post(`/stores/${storeSlug}/checkout`)
        .set('X-Forwarded-For', nextCheckoutIp())
        .field('deliveryMethodType', 'COURIER')
        .field('courierName', courierName)
        .field('courierModality', courierModality)
        .field('customerPhone', '+51970000004')
        .field(
          'items',
          JSON.stringify([
            { productId, variantId: productVariantId, quantity: 1 },
          ]),
        )
        .field('paymentType', 'PARTIAL')
        .field('paymentMethod', 'TRANSFER')
        .field(
          'shippingAddress',
          JSON.stringify({
            recipientName: 'Jane Doe',
            phone: '+51970000004',
            line1: 'Av. Principal 123',
            city: 'Lima',
          }),
        )
        .attach('file', pngBuffer, 'proof.png')
        .expect(201);
      const orderId = res.body.order.id as string;
      orderIds.push(orderId);
      // 25 item + 10 legacy estimatedCost = 35; 20% deposit = 7.
      expect(Number(res.body.order.totalAmount)).toBe(35);
      expect(Number(res.body.order.requiredAmount)).toBe(7);
    });

    it('records an OrderPayment for exactly the requiredAmount', async () => {
      await upsertPaymentMethod({
        method: 'TRANSFER',
        enabled: true,
        details: {
          bankName: 'BCP',
          accountNumber: '444',
          accountHolder: 'E2E',
        },
        depositPercent: 20,
      });
      const res = await partialCheckout(
        '+51970000005',
        { paymentMethod: 'TRANSFER' },
        pngBuffer,
      ).expect(201);
      const orderId = res.body.order.id as string;
      orderIds.push(orderId);

      const payments = await prisma.orderPayment.findMany({
        where: { orderId },
      });
      expect(payments).toHaveLength(1);
      expect(payments[0]!.reviewStatus).toBe('PENDING_REVIEW');
      expect(Number(payments[0]!.amount)).toBe(
        Number(res.body.order.requiredAmount),
      );
      // Clean up the proof image this test uploaded to object storage.
      await storage.deleteImage(payments[0]!.imageUrl!);
    });
  });

  // Regression coverage for the float-precision bug in
  // `OrderRepository.withPaymentSummary` (see
  // docs/plans/2026-08-06-order-payment-precision-bug-fix-plan.md). Splits
  // payment in two so it actually exercises the Decimal-subtraction path a
  // single full payment never touches.
  it('accepts a second partial payment for exactly the displayed pendingAmount on a 99.99 order and reaches VERIFIED', async () => {
    const precisionProductRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set('Cookie', sessionCookie)
      .send({
        name: 'E2E Precision Product',
        price: 33.33,
        currency: 'PEN',
        stock: 100,
      })
      .expect(201);
    const precisionProductId = precisionProductRes.body.id;
    const precisionVariantId = precisionProductRes.body.variants[0].id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${precisionProductId}/publish`)
      .set('Cookie', sessionCookie)
      .expect(200);

    const checkoutRes = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'PICKUP')
      .field('customerPhone', '+51955555555')
      .field(
        'items',
        JSON.stringify([
          {
            productId: precisionProductId,
            variantId: precisionVariantId,
            quantity: 3,
          },
        ]),
      )
      .expect(201);
    const orderId = checkoutRes.body.order.id as string;
    orderIds.push(orderId);
    expect(checkoutRes.body.order.requiredAmount).toBe('99.99');

    const firstPaymentRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/orders/${orderId}/payments`)
      .set('Cookie', sessionCookie)
      .field('amount', '40.00')
      .field('method', 'YAPE')
      .expect(201);
    expect(firstPaymentRes.body.paymentStatus).toBe('PARTIALLY_PAID');
    // The exact regression value: under the old Number-subtraction bug this
    // was `59.989999999999995`, not `59.99`.
    expect(firstPaymentRes.body.pendingAmount).toBe(59.99);

    const pendingAmount = firstPaymentRes.body.pendingAmount as number;
    const secondPaymentRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/orders/${orderId}/payments`)
      .set('Cookie', sessionCookie)
      .field('amount', String(pendingAmount))
      .field('method', 'TRANSFER')
      .expect(201);

    expect(secondPaymentRes.body.paymentStatus).toBe('VERIFIED');
    expect(secondPaymentRes.body.pendingAmount).toBe(0);

    // afterAll's cleanup only tracks the single beforeAll-created `productId`
    // — this order's items reference `precisionProductId` instead, so they'd
    // otherwise survive and block afterAll's `product.deleteMany` with a
    // dangling `OrderItem_productId_fkey`.
    await prisma.orderItem.deleteMany({ where: { orderId } });
    await prisma.orderPayment.deleteMany({ where: { orderId } });
    await prisma.order.deleteMany({ where: { id: orderId } });
    orderIds.splice(orderIds.indexOf(orderId), 1);
    await prisma.productVariant.deleteMany({
      where: { productId: precisionProductId },
    });
    await prisma.product.deleteMany({ where: { id: precisionProductId } });
  });

  // Issue #84: the checkout step accepts the buyer's proof-of-payment upload
  // for manual methods (YAPE/PLIN/TRANSFER) and registers it as a
  // BUYER_SUBMITTED/PENDING_REVIEW OrderPayment. It must not change
  // paymentStatus (still PENDING_PAYMENT, paidAmount 0) until the seller
  // reviews it — the proof is a placeholder the seller can approve/reject
  // via the same review flow.
  it('checkout with a manual payment method + proof attaches a PENDING_REVIEW payment', async () => {
    const orderId = await checkout('+51988888888', {
      paymentMethod: 'YAPE',
      proof: pdfBuffer,
      proofName: 'proof.pdf',
    });

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(findOneRes.body.paymentStatus).toBe('PENDING_PAYMENT');
    expect(findOneRes.body.paidAmount).toBe(0);
    expect(findOneRes.body.payments).toHaveLength(1);
    expect(findOneRes.body.payments[0]).toMatchObject({
      amount: findOneRes.body.totalAmount,
      method: 'YAPE',
      source: 'BUYER_SUBMITTED',
      reviewStatus: 'PENDING_REVIEW',
    });
    uploadedPaymentImageUrl = findOneRes.body.payments[0].imageUrl;
  });

  it('checkout with a PNG proof for a manual method is accepted', async () => {
    const orderId = await checkout('+51988888887', {
      paymentMethod: 'TRANSFER',
      proof: pngBuffer,
      proofName: 'proof.png',
    });

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(findOneRes.body.payments[0].reviewStatus).toBe('PENDING_REVIEW');
    uploadedPaymentImageUrl = findOneRes.body.payments[0].imageUrl;
  });

  it('checkout with a manual payment method but no proof 400s', async () => {
    // The suite never configures real payment-method details elsewhere, so
    // every method (including PLIN) is enabled-but-unconfigured by default —
    // exactly the case checkout now lets through without a proof. Configure
    // real PLIN details first so this still exercises the "configured
    // method, missing proof" 400 path it was written for.
    await request(app.getHttpServer())
      .post(`/stores/${storeId}/payment-methods`)
      .set('Cookie', sessionCookie)
      .send({
        method: 'PLIN',
        enabled: true,
        details: { phoneNumber: '+51988888886', accountHolder: 'E2E Seller' },
      })
      .expect(201);

    const res = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'PICKUP')
      .field('customerPhone', '+51988888886')
      .field('paymentMethod', 'PLIN')
      .field(
        'items',
        JSON.stringify([
          { productId, variantId: productVariantId, quantity: 1 },
        ]),
      )
      .expect(400);
    expect(res.body.message).toContain('Adjunta un comprobante de pago');
  });

  it('checkout with an unconfigured (enabled but no real details) manual payment method succeeds without a proof', async () => {
    const orderId = await checkout('+51988888882', {
      paymentMethod: 'YAPE',
    });

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(findOneRes.body.paymentMethod).toBe('YAPE');
    expect(findOneRes.body.paymentStatus).toBe('PENDING_PAYMENT');
    expect(findOneRes.body.payments).toHaveLength(0);
  });

  it('checkout with a proof in an unsupported format 400s', async () => {
    const res = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'PICKUP')
      .field('customerPhone', '+51988888885')
      .field('paymentMethod', 'YAPE')
      .field(
        'items',
        JSON.stringify([
          { productId, variantId: productVariantId, quantity: 1 },
        ]),
      )
      .attach('file', Buffer.from('not an image at all'), 'proof.txt')
      .expect(400);
    expect(res.body.message).toContain('Solo JPEG, PNG o PDF');
  });

  it('checkout with an oversized proof 400s', async () => {
    const oversized = Buffer.alloc(5 * 1024 * 1024 + 1);
    oversized[0] = 0xff;
    oversized[1] = 0xd8;
    const res = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .set('X-Forwarded-For', nextCheckoutIp())
      .field('deliveryMethodType', 'PICKUP')
      .field('customerPhone', '+51988888884')
      .field('paymentMethod', 'YAPE')
      .field(
        'items',
        JSON.stringify([
          { productId, variantId: productVariantId, quantity: 1 },
        ]),
      )
      .attach('file', oversized, 'proof.jpg')
      .expect(400);
    expect(res.body.message).toContain('Máximo 5MB');
  });

  it('checkout as CASH without a proof succeeds and registers no payment', async () => {
    const orderId = await checkout('+51988888883', {
      paymentMethod: 'CASH',
    });

    const findOneRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/orders/${orderId}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(findOneRes.body.paymentStatus).toBe('PENDING_PAYMENT');
    expect(findOneRes.body.payments).toHaveLength(0);
  });

  // Regression coverage for the stock-hold race condition (HIGH severity —
  // see docs/plans/2026-08-08-orders-module-hardening-plan.md Problem 1):
  // create-order.usecase.ts's variant-availability check used to be a plain
  // findUnique + update with no row lock, so two concurrent checkouts for
  // the same limited-stock variant could both pass the "is there stock"
  // check before either write committed. Requires a real Postgres
  // transaction/locking semantics, so unlike the rest of this file this
  // can't be simulated against the unit suite's fake PrismaService.
  it('concurrent checkouts for a stock=1 variant: exactly one succeeds, the other gets a clean rejection', async () => {
    const raceProductRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set('Cookie', sessionCookie)
      .send({
        name: 'E2E Race Product',
        price: 10,
        currency: 'PEN',
        stock: 1,
      })
      .expect(201);
    const raceProductId = raceProductRes.body.id;
    const raceVariantId = raceProductRes.body.variants[0].id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${raceProductId}/publish`)
      .set('Cookie', sessionCookie)
      .expect(200);

    const attemptCheckout = (customerPhone: string) =>
      request(app.getHttpServer())
        .post(`/stores/${storeSlug}/checkout`)
        .set('X-Forwarded-For', nextCheckoutIp())
        .field('deliveryMethodType', 'PICKUP')
        .field('customerPhone', customerPhone)
        .field(
          'items',
          JSON.stringify([
            { productId: raceProductId, variantId: raceVariantId, quantity: 1 },
          ]),
        );

    const [resA, resB] = await Promise.all([
      attemptCheckout('+51977777771'),
      attemptCheckout('+51977777772'),
    ]);

    const succeeded = [resA, resB].filter((r) => r.status === 201);
    const rejected = [resA, resB].filter((r) => r.status === 400);
    expect(succeeded).toHaveLength(1);
    expect(rejected).toHaveLength(1);
    expect(rejected[0]!.body.message).toContain('Stock insuficiente');

    const winningOrderId = succeeded[0]!.body.order.id as string;

    const variant = await prisma.productVariant.findUniqueOrThrow({
      where: { id: raceVariantId },
    });
    expect(variant.reserved).toBe(1);
    expect(variant.stock).toBe(1);

    await prisma.orderItem.deleteMany({ where: { orderId: winningOrderId } });
    await prisma.order.deleteMany({ where: { id: winningOrderId } });
    await prisma.productVariant.deleteMany({
      where: { productId: raceProductId },
    });
    await prisma.product.deleteMany({ where: { id: raceProductId } });
  });
});
