import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real payment-method-config responses (private CRUD + the
// `?enabled=1` query-filtered branch + public read-only sibling) against
// the schema generated by `pnpm --filter api generate:openapi`
// (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const paymentMethodSchema =
  openapi.components.schemas.PaymentMethodConfigResponseDto;

describe("payment-config (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let storeSlug: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `payment-config-e2e-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    storeSlug = `payment-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (storeId) {
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("findAll/upsert/?enabled=1 filter/public findEnabled match PaymentMethodConfigResponseDto", async () => {
    // Store.create auto-creates all 4 methods enabled (see StoresService.create).
    const listRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/payment-methods`)
      .set("Cookie", sessionCookie)
      .expect(200);
    expect(listRes.body).toHaveLength(4);
    for (const method of listRes.body) {
      assertMatchesSchema(method, paymentMethodSchema, openapi.components);
    }

    const upsertRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/payment-methods`)
      .set("Cookie", sessionCookie)
      .send({ method: "CASH", enabled: false })
      .expect(201);
    assertMatchesSchema(
      upsertRes.body,
      paymentMethodSchema,
      openapi.components,
    );
    expect(upsertRes.body.enabled).toBe(false);

    // The `?enabled=1` branch — dropped silently by a generated client if
    // this endpoint's @ApiQuery decorator is ever removed.
    const enabledRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/payment-methods?enabled=1`)
      .set("Cookie", sessionCookie)
      .expect(200);
    expect(enabledRes.body).toHaveLength(3);
    expect(
      enabledRes.body.some((m: { method: string }) => m.method === "CASH"),
    ).toBe(false);
    for (const method of enabledRes.body) {
      assertMatchesSchema(method, paymentMethodSchema, openapi.components);
    }

    const publicRes = await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/public/payment-methods`)
      .expect(200);
    expect(publicRes.body).toHaveLength(3);
    for (const method of publicRes.body) {
      assertMatchesSchema(method, paymentMethodSchema, openapi.components);
    }
  });
});
