import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real pickup-point responses (private CRUD + public read-only
// sibling) against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const pickupPointSchema = openapi.components.schemas.PickupPointResponseDto;

describe("pickup-points (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let storeSlug: string;
  let pointId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `pickup-points-e2e-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    storeSlug = `pickup-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (pointId) {
      await prisma.pickupPoint.deleteMany({ where: { id: pointId } });
    }
    if (storeId) {
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("create/findAll/update/remove/public findEnabled match PickupPointResponseDto", async () => {
    const createRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/pickup-points`)
      .set("Cookie", sessionCookie)
      .send({
        label: "E2E Pickup Point",
        sortOrder: 1,
        openDays: [1, 2, 3, 4, 5],
        closedOverride: false,
      })
      .expect(201);
    pointId = createRes.body.id;
    assertMatchesSchema(createRes.body, pickupPointSchema, openapi.components);
    expect(createRes.body.label).toBe("E2E Pickup Point");
    expect(createRes.body.openDays).toEqual([1, 2, 3, 4, 5]);
    expect(createRes.body.closedOverride).toBe(false);

    const listRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/pickup-points`)
      .set("Cookie", sessionCookie)
      .expect(200);
    expect(Array.isArray(listRes.body)).toBe(true);
    for (const point of listRes.body) {
      assertMatchesSchema(point, pickupPointSchema, openapi.components);
    }

    const publicRes = await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/public/pickup-points`)
      .expect(200);
    expect(Array.isArray(publicRes.body.points)).toBe(true);
    expect(typeof publicRes.body.weekday).toBe("number");
    expect(publicRes.body.weekday).toBeGreaterThanOrEqual(0);
    expect(publicRes.body.weekday).toBeLessThanOrEqual(6);
    expect(publicRes.body.points.some((p: { id: string }) => p.id === pointId))
      .toBe(true);
    for (const point of publicRes.body.points) {
      assertMatchesSchema(point, pickupPointSchema, openapi.components);
    }

    const updateRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/pickup-points/${pointId}`)
      .set("Cookie", sessionCookie)
      .send({
        label: "Updated E2E Pickup Point",
        openDays: [0, 6],
        closedOverride: true,
      })
      .expect(200);
    assertMatchesSchema(updateRes.body, pickupPointSchema, openapi.components);
    expect(updateRes.body.label).toBe("Updated E2E Pickup Point");
    expect(updateRes.body.openDays).toEqual([0, 6]);
    expect(updateRes.body.closedOverride).toBe(true);

    const removeRes = await request(app.getHttpServer())
      .delete(`/stores/${storeId}/pickup-points/${pointId}`)
      .set("Cookie", sessionCookie)
      .expect(200);
    assertMatchesSchema(removeRes.body, pickupPointSchema, openapi.components);
    pointId = "";
  });

  // Regression coverage for CreateOrderUseCase's defense-in-depth check (see
  // docs/plans/2026-08-06-pickup-point-availability-schema-and-api.md): a
  // direct API call selecting a closedOverride'd point must 400, not create
  // an order against a point the storefront wouldn't have shown as
  // selectable.
  it("rejects checkout against a closedOverride'd pickup point", async () => {
    const closedPointRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/pickup-points`)
      .set("Cookie", sessionCookie)
      .send({ label: "Closed Today", closedOverride: true })
      .expect(201);
    const closedPointId = closedPointRes.body.id as string;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set("Cookie", sessionCookie)
      .send({ name: "E2E Pickup Product", price: 10, currency: "PEN" })
      .expect(201);
    const productId = productRes.body.id as string;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set("Cookie", sessionCookie)
      .expect(200);

    await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .send({
        deliveryMethodType: "PICKUP",
        customerPhone: "+51977777777",
        pickupPointId: closedPointId,
        items: [{ productId, quantity: 1 }],
      })
      .expect(400);

    await prisma.product.deleteMany({ where: { id: productId } });
    await prisma.pickupPoint.deleteMany({ where: { id: closedPointId } });
  });
});
