import { Test, TestingModule } from "@nestjs/testing";
import { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import { StorageService } from "../src/storage/storage.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real product responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json) — this is the
// money/upload gate module (see docs/plans/2026-08-04-orval-client-rollout-plan.md),
// so this test exercises both the `price`/`priceOverride` Decimal-as-string
// convention and (separately, via a plain multipart POST, not the generated
// client) the image upload endpoint.
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const productWithVariantsSchema =
  openapi.components.schemas.ProductWithVariantsResponseDto;
const productDetailSchema = openapi.components.schemas.ProductDetailResponseDto;
const variantSchema = openapi.components.schemas.VariantResponseDto;

describe("products (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let storage: StorageService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let productId: string;
  let variantId: string;
  let uploadedImageUrl: string | undefined;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `products-e2e-${runId}@example.com`;
  const storeSlug = `products-e2e-${runId}`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);
    storage = moduleFixture.get(StorageService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (uploadedImageUrl) await storage.deleteImage(uploadedImageUrl);
    if (productId) {
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.productCategory.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("POST /stores/:storeId/products matches ProductWithVariantsResponseDto, price is a string", async () => {
    const res = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set("Cookie", sessionCookie)
      .send({ name: "E2E Product", price: 19.99, currency: "USD", stock: 5 })
      .expect(201);
    productId = res.body.id;
    variantId = res.body.variants[0].id;

    expect(typeof res.body.price).toBe("string");
    assertMatchesSchema(
      res.body,
      productWithVariantsSchema,
      openapi.components,
    );
  });

  it("GET /stores/:storeId/products matches ProductDetailResponseDto[], priceOverride is a string", async () => {
    if (!productId || !variantId) {
      throw new Error(
        "productId/variantId not set — the product-creation test above must run first and succeed",
      );
    }

    const variantRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/variants/${variantId}`)
      .set("Cookie", sessionCookie)
      .send({ priceOverride: 24.5 })
      .expect(200);

    expect(typeof variantRes.body.priceOverride).toBe("string");
    assertMatchesSchema(variantRes.body, variantSchema, openapi.components);

    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/products`)
      .set("Cookie", sessionCookie)
      .expect(200);

    expect(Array.isArray(res.body)).toBe(true);
    const created = res.body.find((p: { id: string }) => p.id === productId);
    expect(created).toBeDefined();

    for (const product of res.body) {
      assertMatchesSchema(product, productDetailSchema, openapi.components);
    }
  });

  it("POST .../images uploads and returns ProductResponseDto with the new image URL", async () => {
    if (!productId) {
      throw new Error(
        "productId not set — the product-creation test above must run first and succeed",
      );
    }

    // 1x1 PNG, smallest valid file that passes the controller's magic-byte check.
    const pngBuffer = Buffer.from(
      "89504e470d0a1a0a0000000d4948445200000001000000010802000000907753de0000000c4944415478da6360606060000000050001a5f645400000000049454e44ae426082",
      "hex",
    );

    const res = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products/${productId}/images`)
      .set("Cookie", sessionCookie)
      .attach("file", pngBuffer, "pixel.png")
      .expect(201);

    uploadedImageUrl = res.body.images[res.body.images.length - 1];

    expect(Array.isArray(res.body.images)).toBe(true);
    expect(res.body.images.length).toBeGreaterThan(0);
    assertMatchesSchema(
      res.body,
      { ...openapi.components.schemas.ProductResponseDto },
      openapi.components,
    );
  });
});
