import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real ProductSearch responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const resultSchema = openapi.components.schemas.ProductSearchResultResponseDto;

describe("product search (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sellerSessionCookie: string;
  let sellerUserId: string;
  let storeId: string;
  let productId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const sellerEmail = `product-search-e2e-seller-${runId}@example.com`;
  const productName = `E2E Searchable Product ${runId}`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email: sellerEmail, password, name: "E2E Seller" })
      .expect(200);
    sellerUserId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(
      existingMailerFiles,
      sellerEmail,
    );
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email: sellerEmail, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sellerSessionCookie = raw.split(";")[0]!;

    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sellerSessionCookie)
      .send({
        name: "E2E Store",
        slug: `product-search-e2e-${runId}`,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set("Cookie", sellerSessionCookie)
      .send({
        name: productName,
        price: 15.5,
        currency: "PEN",
        stock: 100,
      })
      .expect(201);
    productId = productRes.body.id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);
  });

  afterAll(async () => {
    if (productId) {
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (sellerUserId) {
      await prisma.user.deleteMany({ where: { id: sellerUserId } });
    }
    await app.close();
  });

  it("GET /products/search matches ProductSearchResultResponseDto", async () => {
    const res = await request(app.getHttpServer())
      .get(`/products/search?q=${encodeURIComponent(productName)}`)
      .expect(200);
    assertMatchesSchema(res.body, resultSchema, openapi.components);
    expect(res.body.products).toHaveLength(1);
    const found = res.body.products[0];
    expect(found.id).toBe(productId);
    expect(typeof found.price).toBe("string");
    expect(found.store.slug).toBeDefined();
  });

  it("respects page/limit query params", async () => {
    const res = await request(app.getHttpServer())
      .get(`/products/search?q=${encodeURIComponent(productName)}&page=1&limit=1`)
      .expect(200);
    assertMatchesSchema(res.body, resultSchema, openapi.components);
    expect(res.body.page).toBe(1);
    expect(res.body.limit).toBe(1);
  });
});
