import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from "./schema-assert.js";

// Validates real Stats responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
// `getOverview`'s `recentOrders` reuses `Order`'s own `OrderResponseDto` (see
// stats-response.dto.ts's comment) — same shared-shape reasoning as
// `Customers`, since `StatsService.getOverview` runs the same
// `withPaymentSummary`-over-`{items, payments}` include.
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const overviewSchema = openapi.components.schemas.StatsOverviewResponseDto;
const analyticsSchema = openapi.components.schemas.AnalyticsResultResponseDto;

describe("stats (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sellerSessionCookie: string;
  let sellerUserId: string;
  let storeId: string;
  let storeSlug: string;
  let productId: string;
  let orderId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const sellerEmail = `stats-e2e-seller-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email: sellerEmail, password, name: "E2E Seller" })
      .expect(200);
    sellerUserId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(
      existingMailerFiles,
      sellerEmail,
    );
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email: sellerEmail, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sellerSessionCookie = raw.split(";")[0]!;

    storeSlug = `stats-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sellerSessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set("Cookie", sellerSessionCookie)
      .send({ name: "E2E Product", price: 30, currency: "PEN", stock: 100 })
      .expect(201);
    productId = productRes.body.id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);

    const checkoutRes = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .send({
        deliveryMethodType: "PICKUP",
        customerPhone: "+51988888888",
        items: [{ productId, quantity: 1 }],
      })
      .expect(201);
    orderId = checkoutRes.body.order.id as string;

    await request(app.getHttpServer())
      .post(`/stores/${storeId}/orders/${orderId}/payments`)
      .set("Cookie", sellerSessionCookie)
      .field("amount", "30")
      .field("method", "YAPE")
      .expect(201);
  });

  afterAll(async () => {
    if (orderId) {
      await prisma.orderPayment.deleteMany({ where: { orderId } });
      await prisma.orderItem.deleteMany({ where: { orderId } });
      await prisma.order.deleteMany({ where: { id: orderId } });
    }
    if (productId) {
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (sellerUserId) {
      await prisma.user.deleteMany({ where: { id: sellerUserId } });
    }
    await app.close();
  });

  it("GET /stats/overview matches StatsOverviewResponseDto", async () => {
    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/stats/overview`)
      .set("Cookie", sellerSessionCookie)
      .expect(200);
    assertMatchesSchema(res.body, overviewSchema, openapi.components);
    expect(res.body.revenue).toBe(30);
    expect(res.body.totalOrders).toBe(1);
    expect(res.body.paymentStatusCounts.VERIFIED).toBe(1);
    const recentOrder = res.body.recentOrders.find(
      (o: { id: string }) => o.id === orderId,
    );
    expect(recentOrder).toBeDefined();
    expect(typeof recentOrder.totalAmount).toBe("string");
    expect(recentOrder.paidAmount).toBe(30);
    expect(recentOrder.items).toHaveLength(1);
  });

  it("GET /stats/analytics matches AnalyticsResultResponseDto for each range", async () => {
    for (const range of ["30d", "90d", "12m"]) {
      const res = await request(app.getHttpServer())
        .get(`/stores/${storeId}/stats/analytics?range=${range}`)
        .set("Cookie", sellerSessionCookie)
        .expect(200);
      assertMatchesSchema(res.body, analyticsSchema, openapi.components);
      expect(res.body.range).toBe(range);
      expect(Array.isArray(res.body.buckets)).toBe(true);
      expect(Array.isArray(res.body.topProducts)).toBe(true);
    }
  });

  it("400s on an invalid range", async () => {
    await request(app.getHttpServer())
      .get(`/stores/${storeId}/stats/analytics?range=invalid`)
      .set("Cookie", sellerSessionCookie)
      .expect(400);
  });
});
