import { Test, type TestingModule } from "@nestjs/testing";
import type { INestApplication } from "@nestjs/common";
import { PrismaService } from "../src/prisma/prisma.service.js";
import request from "supertest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AppModule } from "./../src/app.module.js";
import { mailerDevDir, waitForNewMailerFile } from "./schema-assert.js";

// Validates real store-section responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json).
const openapiPath = join(__dirname, "..", "openapi.json");
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, "utf-8");
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const sectionSchema = {
  ...openapi.components.schemas.StoreSectionResponseDto,
  components: openapi.components,
};

function assertMatchesSchema(
  value: unknown,
  schema: Record<string, unknown>,
  components: Record<string, unknown>,
  path = "$",
): void {
  const resolved = resolveSchema(schema, components);
  if (resolved.type === "object") {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      throw new Error(`${path}: expected object, got ${JSON.stringify(value)}`);
    }
    const properties = (resolved.properties ?? {}) as Record<string, unknown>;
    const required = (resolved.required ?? []) as string[];
    for (const key of required) {
      if (!(key in (value as Record<string, unknown>))) {
        throw new Error(`${path}: missing required property "${key}"`);
      }
    }
    for (
      const [key, propValue] of Object.entries(value as Record<string, unknown>)
    ) {
      const propSchema = properties[key];
      if (!propSchema) {
        if (resolved.additionalProperties) continue;
        throw new Error(`${path}.${key}: property not declared in schema`);
      }
      assertMatchesSchema(
        propValue,
        propSchema as Record<string, unknown>,
        components,
        `${path}.${key}`,
      );
    }
    return;
  }
  if (resolved.type === "array") {
    if (!Array.isArray(value)) {
      throw new Error(`${path}: expected array, got ${JSON.stringify(value)}`);
    }
    value.forEach((item, i) =>
      assertMatchesSchema(
        item,
        resolved.items as Record<string, unknown>,
        components,
        `${path}[${i}]`,
      )
    );
    return;
  }
  if (resolved.nullable && value === null) return;
  if (resolved.type === "string" && typeof value !== "string") {
    throw new Error(`${path}: expected string, got ${JSON.stringify(value)}`);
  }
  if (resolved.type === "number" && typeof value !== "number") {
    throw new Error(`${path}: expected number, got ${JSON.stringify(value)}`);
  }
  if (resolved.type === "boolean" && typeof value !== "boolean") {
    throw new Error(`${path}: expected boolean, got ${JSON.stringify(value)}`);
  }
}

function resolveSchema(
  schema: Record<string, unknown>,
  components: Record<string, unknown>,
): Record<string, unknown> {
  const ref = schema.$ref as string | undefined;
  if (!ref) return schema;
  const name = ref.replace("#/components/schemas/", "");
  const schemas = (components as { schemas: Record<string, unknown> }).schemas;
  return schemas[name] as Record<string, unknown>;
}

describe("store-sections (e2e)", () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let sectionId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `sections-e2e-${runId}@example.com`;
  const storeSlug = `sections-e2e-${runId}`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = "correcthorsebatterystaple";
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post("/api/auth/sign-up/email")
      .send({ email, password, name: "E2E Seller" })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, "utf-8");
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error("verification link not found in email");
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post("/api/auth/sign-in/email")
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers["set-cookie"] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes("session_token"));
    if (!raw) throw new Error("sign-in did not return a session cookie");
    sessionCookie = raw.split(";")[0]!;

    const storeRes = await request(app.getHttpServer())
      .post("/stores")
      .set("Cookie", sessionCookie)
      .send({
        name: "E2E Store",
        slug: storeSlug,
        whatsappNumber: "+51900000000",
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (storeId) {
      await prisma.storeSection.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it("create/findAll/update/reorder/delete match the generated openapi.json schema", async () => {
    const createRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/sections`)
      .set("Cookie", sessionCookie)
      .send({ type: "TEXT_BLOCK", content: { body: "E2E section body" } })
      .expect(201);
    sectionId = createRes.body.id;
    assertMatchesSchema(createRes.body, sectionSchema, openapi.components);
    expect(createRes.body.type).toBe("TEXT_BLOCK");

    const listRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/sections`)
      .set("Cookie", sessionCookie)
      .expect(200);
    expect(Array.isArray(listRes.body)).toBe(true);
    const created = listRes.body.find(
      (s: { id: string }) => s.id === sectionId,
    );
    expect(created).toBeDefined();
    for (const section of listRes.body) {
      assertMatchesSchema(section, sectionSchema, openapi.components);
    }

    const updateRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/sections/${sectionId}`)
      .set("Cookie", sessionCookie)
      .send({ content: { body: "Updated E2E section body" } })
      .expect(200);
    assertMatchesSchema(updateRes.body, sectionSchema, openapi.components);
    expect(updateRes.body.content.body).toBe("Updated E2E section body");

    const reorderRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}/sections/reorder`)
      .set("Cookie", sessionCookie)
      .send({ sectionIds: [sectionId] })
      .expect(200);
    expect(Array.isArray(reorderRes.body)).toBe(true);
    for (const section of reorderRes.body) {
      assertMatchesSchema(section, sectionSchema, openapi.components);
    }

    const deleteRes = await request(app.getHttpServer())
      .delete(`/stores/${storeId}/sections/${sectionId}`)
      .set("Cookie", sessionCookie)
      .expect(200);
    assertMatchesSchema(deleteRes.body, sectionSchema, openapi.components);
    sectionId = "";
  });
});
