import { Test, type TestingModule } from '@nestjs/testing';
import type { INestApplication } from '@nestjs/common';
import { PrismaService } from '../src/prisma/prisma.service.js';
import { StorageService } from '../src/storage/storage.service.js';
import request from 'supertest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { AppModule } from './../src/app.module.js';
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from './schema-assert.js';

// Validates real Stores/MyStores responses against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json) — the
// riskiest module in Batch 3 (see
// docs/plans/2026-08-05-orval-rollout-batches-3-6-plan.md): a logo upload
// (money/upload-gate-shaped, like products) plus several deeply-nested
// public join shapes (findPublicBySlug's section->collection->products
// join in particular). This spec builds a real
// category/product/collection/section graph so findPublicBySlug exercises
// the actual nested-join path, not just the "no sections yet" orphan
// fallback.
const openapiPath = join(__dirname, '..', 'openapi.json');
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, 'utf-8');
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const storeSchema = openapi.components.schemas.StoreResponseDto;
const storeWithOwnerSchema =
  openapi.components.schemas.StoreWithOwnerResponseDto;
const publicStoreListingSchema =
  openapi.components.schemas.PublicStoreListingResponseDto;
const sitemapStoreCountSchema = openapi.components.schemas.SitemapStoreCountDto;
const sitemapStorePageSchema = openapi.components.schemas.SitemapStorePageDto;
const publicCollectionListingSchema =
  openapi.components.schemas.PublicCollectionListingResponseDto;
const featuredStoreSchema = openapi.components.schemas.FeaturedStoreResponseDto;
const storeDirectorySchema =
  openapi.components.schemas.StoreDirectoryResponseDto;
const publicCategorySchema =
  openapi.components.schemas.PublicCategoryResponseDto;
const publicProductPageSchema =
  openapi.components.schemas.PublicProductPageResponseDto;
const storePublicDetailSchema =
  openapi.components.schemas.StorePublicDetailResponseDto;

describe('stores + my-stores (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let storage: StorageService;
  let sessionCookie: string;
  let userId: string;
  let storeId: string;
  let storeSlug: string;
  let categoryId: string;
  let productId: string;
  let collectionId: string;
  let sectionId: string;
  let uploadedLogoUrl: string | undefined;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `stores-e2e-${runId}@example.com`;

  beforeAll(async () => {
    process.env.SITEMAP_INTERNAL_TOKEN ??= 'e2e-sitemap-token';
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);
    storage = moduleFixture.get(StorageService);

    const password = 'correcthorsebatterystaple';
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post('/api/auth/sign-up/email')
      .send({ email, password, name: 'E2E Seller' })
      .expect(200);
    userId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
    const html = readFileSync(mailerFile, 'utf-8');
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error('verification link not found in email');
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    const signInRes = await request(app.getHttpServer())
      .post('/api/auth/sign-in/email')
      .send({ email, password })
      .expect(200);
    const setCookie = signInRes.headers['set-cookie'] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes('session_token'));
    if (!raw) throw new Error('sign-in did not return a session cookie');
    sessionCookie = raw.split(';')[0]!;

    storeSlug = `stores-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post('/stores')
      .set('Cookie', sessionCookie)
      .send({
        name: 'E2E Store',
        slug: storeSlug,
        whatsappNumber: '+51900000000',
      })
      .expect(201);
    storeId = storeRes.body.id;
    assertMatchesSchema(storeRes.body, storeSchema, openapi.components);
  });

  afterAll(async () => {
    if (uploadedLogoUrl) await storage.deleteImage(uploadedLogoUrl);
    if (sectionId) await prisma.storeSection.deleteMany({ where: { storeId } });
    if (collectionId) {
      await prisma.collectionProduct.deleteMany({ where: { collectionId } });
      await prisma.collection.deleteMany({ where: { id: collectionId } });
    }
    if (productId) {
      await prisma.productVariant.deleteMany({ where: { productId } });
      await prisma.productCategory.deleteMany({ where: { productId } });
      await prisma.product.deleteMany({ where: { id: productId } });
    }
    if (categoryId) {
      await prisma.category.deleteMany({ where: { id: categoryId } });
    }
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it('MyStores.findMine matches StoreResponseDto[] and includes the created store', async () => {
    const res = await request(app.getHttpServer())
      .get('/me/stores')
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(Array.isArray(res.body)).toBe(true);
    expect(res.body.some((s: { id: string }) => s.id === storeId)).toBe(true);
    for (const store of res.body) {
      assertMatchesSchema(store, storeSchema, openapi.components);
    }
  });

  it('update/findBySlug match StoreResponseDto', async () => {
    const updateRes = await request(app.getHttpServer())
      .patch(`/stores/${storeId}`)
      .set('Cookie', sessionCookie)
      .send({ name: 'E2E Store Updated' })
      .expect(200);
    assertMatchesSchema(updateRes.body, storeSchema, openapi.components);
    expect(updateRes.body.name).toBe('E2E Store Updated');

    const findRes = await request(app.getHttpServer())
      .get(`/stores/by-slug/${storeSlug}`)
      .set('Cookie', sessionCookie)
      .expect(200);
    assertMatchesSchema(findRes.body, storeSchema, openapi.components);
  });

  it('builds a category/product/collection/section graph, then validates every public read', async () => {
    const categoryRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/categories`)
      .set('Cookie', sessionCookie)
      .send({ name: 'E2E Category' })
      .expect(201);
    categoryId = categoryRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set('Cookie', sessionCookie)
      .send({ name: 'E2E Product', price: 25, currency: 'USD', stock: 10 })
      .expect(201);
    productId = productRes.body.id;

    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productId}/publish`)
      .set('Cookie', sessionCookie)
      .expect(200);

    const collectionRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/collections`)
      .set('Cookie', sessionCookie)
      .send({ name: 'E2E Collection' })
      .expect(201);
    collectionId = collectionRes.body.id;

    await request(app.getHttpServer())
      .post(`/stores/${storeId}/collections/${collectionId}/products`)
      .set('Cookie', sessionCookie)
      .send({ productId })
      .expect(201);

    const sectionRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/sections`)
      .set('Cookie', sessionCookie)
      .send({ type: 'COLLECTION', collectionId })
      .expect(201);
    sectionId = sectionRes.body.id;

    // findPublicBySlug — the real nested section->collection->products join,
    // not the orphan-product fallback (see StoresService.findPublicBySlug).
    const publicRes = await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/public`)
      .expect(200);
    assertMatchesSchema(
      publicRes.body,
      storePublicDetailSchema,
      openapi.components,
    );
    const matchingSection = publicRes.body.sections.find(
      (s: { id: string }) => s.id === sectionId,
    );
    expect(matchingSection).toBeDefined();
    expect(matchingSection.collection.products[0].product.id).toBe(productId);
    expect(typeof matchingSection.collection.products[0].product.price).toBe(
      'string',
    );

    const allPublicRes = await request(app.getHttpServer())
      .get('/stores/public')
      .expect(200);
    expect(
      allPublicRes.body.some((s: { slug: string }) => s.slug === storeSlug),
    ).toBe(true);
    for (const entry of allPublicRes.body) {
      assertMatchesSchema(entry, publicStoreListingSchema, openapi.components);
    }

    const sitemapToken = process.env.SITEMAP_INTERNAL_TOKEN;
    const countRes = await request(app.getHttpServer())
      .get('/stores/internal/sitemap/count')
      .set('X-Internal-Sitemap-Token', sitemapToken!)
      .expect(200);
    assertMatchesSchema(
      countRes.body,
      sitemapStoreCountSchema,
      openapi.components,
    );
    expect(countRes.body.total).toBeGreaterThanOrEqual(1);

    const pageRes = await request(app.getHttpServer())
      .get('/stores/internal/sitemap?limit=1&offset=0')
      .set('X-Internal-Sitemap-Token', sitemapToken!)
      .expect(200);
    assertMatchesSchema(
      pageRes.body,
      sitemapStorePageSchema,
      openapi.components,
    );
    expect(pageRes.body.items).toEqual([{ slug: expect.any(String) }]);
    expect(pageRes.body.total).toBe(countRes.body.total);

    await request(app.getHttpServer())
      .get('/stores/internal/sitemap?limit=1&offset=0')
      .expect(401);
    await request(app.getHttpServer())
      .get('/stores/internal/sitemap?limit=50001&offset=0')
      .set('X-Internal-Sitemap-Token', sitemapToken!)
      .expect(400);

    const collectionsPublicRes = await request(app.getHttpServer())
      .get('/stores/collections/public')
      .expect(200);
    for (const entry of collectionsPublicRes.body) {
      assertMatchesSchema(
        entry,
        publicCollectionListingSchema,
        openapi.components,
      );
    }

    const categoriesPublicRes = await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/categories/public`)
      .expect(200);
    expect(
      categoriesPublicRes.body.some((c: { id: string }) => c.id === categoryId),
    ).toBe(true);
    for (const entry of categoriesPublicRes.body) {
      assertMatchesSchema(entry, publicCategorySchema, openapi.components);
    }

    const productPublicRes = await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/products/${productId}/public`)
      .expect(200);
    assertMatchesSchema(
      productPublicRes.body,
      publicProductPageSchema,
      openapi.components,
    );
    expect(typeof productPublicRes.body.product.price).toBe('string');

    const directoryRes = await request(app.getHttpServer())
      .get('/stores/directory')
      .expect(200);
    assertMatchesSchema(
      directoryRes.body,
      storeDirectorySchema,
      openapi.components,
    );

    const featuredRes = await request(app.getHttpServer())
      .get('/stores/featured?limit=5')
      .expect(200);
    expect(Array.isArray(featuredRes.body)).toBe(true);
    for (const entry of featuredRes.body) {
      assertMatchesSchema(entry, featuredStoreSchema, openapi.components);
    }
  });

  it('uploadLogo matches StoreResponseDto with the new logo URL', async () => {
    const pngBuffer = Buffer.from(
      '89504e470d0a1a0a0000000d4948445200000001000000010802000000907753de0000000c4944415478da6360606060000000050001a5f645400000000049454e44ae426082',
      'hex',
    );

    const res = await request(app.getHttpServer())
      .post(`/stores/${storeId}/logo`)
      .set('Cookie', sessionCookie)
      .attach('file', pngBuffer, 'logo.png')
      .expect(201);

    uploadedLogoUrl = res.body.logoUrl;
    expect(typeof res.body.logoUrl).toBe('string');
    assertMatchesSchema(res.body, storeSchema, openapi.components);
  });

  it('Stores.findAllForAdmin matches StoreWithOwnerResponseDto[] for an admin user', async () => {
    await prisma.user.update({
      where: { id: userId },
      data: { role: 'admin' },
    });

    const res = await request(app.getHttpServer())
      .get('/stores')
      .set('Cookie', sessionCookie)
      .expect(200);
    expect(res.body.some((s: { id: string }) => s.id === storeId)).toBe(true);
    for (const store of res.body) {
      assertMatchesSchema(store, storeWithOwnerSchema, openapi.components);
    }

    await prisma.user.update({
      where: { id: userId },
      data: { role: 'seller' },
    });
  });

  it('isDemo stores drop out of every public listing but stay reachable by slug (#167)', async () => {
    const isListed = async () => {
      const [directory, allPublic, search, sitemapCount] = await Promise.all([
        request(app.getHttpServer()).get('/stores/directory').expect(200),
        request(app.getHttpServer()).get('/stores/public').expect(200),
        request(app.getHttpServer())
          .get('/products/search?limit=50')
          .expect(200),
        request(app.getHttpServer())
          .get('/stores/internal/sitemap/count')
          .set('X-Internal-Sitemap-Token', process.env.SITEMAP_INTERNAL_TOKEN!)
          .expect(200),
      ]);
      return {
        directory: directory.body.stores.some(
          (s: { id: string }) => s.id === storeId,
        ),
        allPublic: allPublic.body.some(
          (s: { slug: string }) => s.slug === storeSlug,
        ),
        search: search.body.products.some(
          (p: { id: string }) => p.id === productId,
        ),
        sitemapTotal: sitemapCount.body.total as number,
      };
    };

    const before = await isListed();
    expect(before.directory).toBe(true);
    expect(before.allPublic).toBe(true);
    expect(before.search).toBe(true);

    await prisma.store.update({
      where: { id: storeId },
      data: { isDemo: true },
    });

    const after = await isListed();
    expect(after.directory).toBe(false);
    expect(after.allPublic).toBe(false);
    expect(after.search).toBe(false);
    expect(after.sitemapTotal).toBe(before.sitemapTotal - 1);

    // Direct link still resolves — demo stores stay usable for QA.
    await request(app.getHttpServer())
      .get(`/stores/${storeSlug}/public`)
      .expect(200);

    await prisma.store.update({
      where: { id: storeId },
      data: { isDemo: false },
    });
  });

  it('delete: documents a real, pre-existing bug found while writing this spec, not fixed here', async () => {
    // Every store — even a brand-new one with zero products — gets a
    // DeliveryMethodConfig row + 4 PaymentMethodConfig rows auto-created by
    // StoresService.create (see its $transaction). Neither relation has
    // `onDelete: Cascade` in schema.prisma, and StoresService.delete does
    // not clean them up before calling `prisma.store.delete` — so the raw
    // FK constraint always rejects the delete and the service's catch
    // block turns that into a 400 ("tiene productos u órdenes asociadas"),
    // for literally every store, even ones with no products or orders at
    // all. Discovered while giving this endpoint a real response DTO
    // (nothing in the Orval rollout exercised a real delete before); out of
    // scope to fix as part of a DTO-authoring migration (see
    // docs/plans/2026-08-05-orval-rollout-batches-3-6-plan.md's Batch 3
    // section on staying scoped) — flagged here instead of silently
    // asserting a 200 an actual seller could never get today. The row still
    // gets a real StoreResponseDto-shaped 400 body's `message`; the store
    // itself has to be cleaned up directly via Prisma below since the API
    // call never actually deletes it.
    const throwawaySlug = `${storeSlug}-throwaway`;
    const createRes = await request(app.getHttpServer())
      .post('/stores')
      .set('Cookie', sessionCookie)
      .send({
        name: 'E2E Throwaway Store',
        slug: throwawaySlug,
        whatsappNumber: '+51900000000',
      })
      .expect(201);
    const throwawayId = createRes.body.id;

    await request(app.getHttpServer())
      .delete(`/stores/${throwawayId}`)
      .set('Cookie', sessionCookie)
      .expect(400);

    await prisma.paymentMethodConfig.deleteMany({
      where: { storeId: throwawayId },
    });
    await prisma.deliveryMethodConfig.deleteMany({
      where: { storeId: throwawayId },
    });
    await prisma.store.deleteMany({ where: { id: throwawayId } });
  });
});
