import { Test, type TestingModule } from '@nestjs/testing';
import type { INestApplication } from '@nestjs/common';
import { PrismaService } from '../src/prisma/prisma.service.js';
import request from 'supertest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { AppModule } from './../src/app.module.js';
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from './schema-assert.js';

// Validates the real Users response against the schema generated by
// `pnpm --filter api generate:openapi` (apps/api/openapi.json). Admin-gated,
// no `storeId`, no public "become admin" flow — same seeding pattern
// contact.e2e-spec.ts uses.
const openapiPath = join(__dirname, '..', 'openapi.json');
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, 'utf-8');
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const storeCountSchema = openapi.components.schemas.UserStoreCountResponseDto;

describe('users (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let adminSessionCookie: string;
  let adminUserId: string;
  let storeId: string;

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const adminEmail = `users-e2e-admin-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const password = 'correcthorsebatterystaple';
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post('/api/auth/sign-up/email')
      .send({ email: adminEmail, password, name: 'E2E Admin' })
      .expect(200);
    adminUserId = signUpRes.body.user.id;

    const mailerFile = await waitForNewMailerFile(
      existingMailerFiles,
      adminEmail,
    );
    const html = readFileSync(mailerFile, 'utf-8');
    const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
    if (!tokenMatch) throw new Error('verification link not found in email');
    await request(app.getHttpServer())
      .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
      .expect((res) => {
        if (res.status >= 400) {
          throw new Error(`verify-email failed with status ${res.status}`);
        }
      });

    // No public "become admin" flow exists — seeding the role directly via
    // Prisma is the only way to exercise the admin-guarded endpoint below.
    await prisma.user.update({
      where: { id: adminUserId },
      data: { role: 'admin' },
    });

    const signInRes = await request(app.getHttpServer())
      .post('/api/auth/sign-in/email')
      .send({ email: adminEmail, password })
      .expect(200);
    const setCookie = signInRes.headers['set-cookie'] as unknown as string[];
    const raw = setCookie?.find((c) => c.includes('session_token'));
    if (!raw) throw new Error('sign-in did not return a session cookie');
    adminSessionCookie = raw.split(';')[0]!;

    const storeRes = await request(app.getHttpServer())
      .post('/stores')
      .set('Cookie', adminSessionCookie)
      .send({
        name: 'E2E Store',
        slug: `users-e2e-${runId}`,
        whatsappNumber: '+51900000000',
      })
      .expect(201);
    storeId = storeRes.body.id;
  });

  afterAll(async () => {
    if (storeId) {
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (adminUserId) {
      await prisma.user.deleteMany({ where: { id: adminUserId } });
    }
    await app.close();
  });

  it('GET /admin/users/store-counts matches UserStoreCountResponseDto', async () => {
    const res = await request(app.getHttpServer())
      .get('/admin/users/store-counts')
      .set('Cookie', adminSessionCookie)
      .expect(200);
    expect(Array.isArray(res.body)).toBe(true);
    const own = res.body.find(
      (row: { userId: string }) => row.userId === adminUserId,
    );
    expect(own).toBeDefined();
    expect(own.storeCount).toBeGreaterThanOrEqual(1);
    for (const row of res.body) {
      assertMatchesSchema(row, storeCountSchema, openapi.components);
    }
  });

  it('403s for a non-admin session', async () => {
    const password = 'correcthorsebatterystaple';
    const nonAdminEmail = `users-e2e-nonadmin-${runId}@example.com`;
    const existingMailerFiles = new Set(readdirSync(mailerDevDir));

    const signUpRes = await request(app.getHttpServer())
      .post('/api/auth/sign-up/email')
      .send({ email: nonAdminEmail, password, name: 'E2E Non-Admin' })
      .expect(200);
    const nonAdminUserId = signUpRes.body.user.id;

    try {
      const mailerFile = await waitForNewMailerFile(
        existingMailerFiles,
        nonAdminEmail,
      );
      const html = readFileSync(mailerFile, 'utf-8');
      const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
      if (!tokenMatch) throw new Error('verification link not found in email');
      await request(app.getHttpServer())
        .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
        .expect((res) => {
          if (res.status >= 400) {
            throw new Error(`verify-email failed with status ${res.status}`);
          }
        });

      const signInRes = await request(app.getHttpServer())
        .post('/api/auth/sign-in/email')
        .send({ email: nonAdminEmail, password })
        .expect(200);
      const setCookie = signInRes.headers['set-cookie'] as unknown as string[];
      const raw = setCookie?.find((c) => c.includes('session_token'));
      if (!raw) throw new Error('sign-in did not return a session cookie');
      const nonAdminSessionCookie = raw.split(';')[0]!;

      await request(app.getHttpServer())
        .get('/admin/users/store-counts')
        .set('Cookie', nonAdminSessionCookie)
        .expect(403);
    } finally {
      await prisma.user.deleteMany({ where: { id: nonAdminUserId } });
    }
  });
});
