import { Test, type TestingModule } from '@nestjs/testing';
import type { INestApplication } from '@nestjs/common';
import { PrismaService } from '../src/prisma/prisma.service.js';
import request from 'supertest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { AppModule } from './../src/app.module.js';
import {
  assertMatchesSchema,
  mailerDevDir,
  waitForNewMailerFile,
} from './schema-assert.js';

// Validates the per-store WhatsApp message-template override flow against the
// schema generated by `pnpm --filter api generate:openapi`:
//   - GET/PUT stores/:storeId/whatsapp-templates/:type (seller-only CRUD)
//   - required-variable rejection on save (a NEW_ORDER template missing
//     {{orderRef}} must 400, not silently save)
//   - the end-to-end effect: checkout's seller-bound WhatsApp URL renders the
//     store's custom NEW_ORDER template, and a store with no override still
//     gets today's exact hardcoded default (regression).
const openapiPath = join(__dirname, '..', 'openapi.json');
let openapiRaw: string;
try {
  openapiRaw = readFileSync(openapiPath, 'utf-8');
} catch {
  throw new Error(
    `${openapiPath} not found — run "pnpm --filter api generate:openapi" first.`,
  );
}
const openapi = JSON.parse(openapiRaw);
const templateSchema = openapi.components.schemas.WhatsAppTemplateResponseDto;

async function signupAndSignin(
  app: INestApplication,
  email: string,
): Promise<{ cookie: string; userId: string }> {
  const password = 'correcthorsebatterystaple';
  const existingMailerFiles = new Set(readdirSync(mailerDevDir));

  const signUpRes = await request(app.getHttpServer())
    .post('/api/auth/sign-up/email')
    .send({ email, password, name: 'E2E Seller' })
    .expect(200);

  const mailerFile = await waitForNewMailerFile(existingMailerFiles, email);
  const html = readFileSync(mailerFile, 'utf-8');
  const tokenMatch = html.match(/verify-email\?token=([^&"]+)/);
  if (!tokenMatch) throw new Error('verification link not found in email');
  await request(app.getHttpServer())
    .get(`/api/auth/verify-email?token=${tokenMatch[1]}`)
    .expect((res) => {
      if (res.status >= 400) {
        throw new Error(`verify-email failed with status ${res.status}`);
      }
    });

  const signInRes = await request(app.getHttpServer())
    .post('/api/auth/sign-in/email')
    .send({ email, password })
    .expect(200);
  const setCookie = signInRes.headers['set-cookie'] as unknown as string[];
  const raw = setCookie?.find((c) => c.includes('session_token'));
  if (!raw) throw new Error('sign-in did not return a session cookie');
  return { cookie: raw.split(';')[0]!, userId: signUpRes.body.user.id };
}

describe('whatsapp-templates (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let sessionCookie: string;
  let otherSessionCookie: string;
  let userId: string;
  let storeId: string;
  let storeSlug: string;
  let productId: string;
  let productVariantId: string;
  const orderIds: string[] = [];

  const runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const email = `whatsapp-templates-e2e-${runId}@example.com`;
  const otherEmail = `whatsapp-templates-other-${runId}@example.com`;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    prisma = moduleFixture.get(PrismaService);

    const owner = await signupAndSignin(app, email);
    sessionCookie = owner.cookie;
    userId = owner.userId;
    const other = await signupAndSignin(app, otherEmail);
    otherSessionCookie = other.cookie;

    storeSlug = `whatsapp-e2e-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post('/stores')
      .set('Cookie', sessionCookie)
      .send({
        name: 'E2E Store',
        slug: storeSlug,
        whatsappNumber: '+51900000000',
      })
      .expect(201);
    storeId = storeRes.body.id;

    const productRes = await request(app.getHttpServer())
      .post(`/stores/${storeId}/products`)
      .set('Cookie', sessionCookie)
      .send({ name: 'E2E Product', price: 25, currency: 'PEN', stock: 100 })
      .expect(201);
    productId = productRes.body.id;
    productVariantId = productRes.body.variants[0].id;
    await request(app.getHttpServer())
      .patch(`/stores/${storeId}/products/${productRes.body.id}/publish`)
      .set('Cookie', sessionCookie)
      .expect(200);
  });

  afterAll(async () => {
    if (orderIds.length > 0) {
      await prisma.orderItem.deleteMany({
        where: { orderId: { in: orderIds } },
      });
      await prisma.order.deleteMany({ where: { id: { in: orderIds } } });
    }
    if (storeId) {
      await prisma.whatsAppMessageTemplate.deleteMany({ where: { storeId } });
      await prisma.notification.deleteMany({ where: { storeId } });
      await prisma.productVariant.deleteMany({ where: { storeId } });
      await prisma.product.deleteMany({ where: { storeId } });
      await prisma.paymentMethodConfig.deleteMany({ where: { storeId } });
      await prisma.deliveryMethodConfig.deleteMany({ where: { storeId } });
      await prisma.store.deleteMany({ where: { id: storeId } });
    }
    if (userId) await prisma.user.deleteMany({ where: { id: userId } });
    await app.close();
  });

  it('returns no override (Nest serializes a null body as empty)', async () => {
    const res = await request(app.getHttpServer())
      .get(`/stores/${storeId}/whatsapp-templates/NEW_ORDER`)
      .set('Cookie', sessionCookie)
      .expect(200);
    // Nest's express adapter sends an empty body for null/undefined results
    // (isNil → response.send()), so the "no override" marker is an empty
    // body, not a JSON `null`. The generated client's customFetch keeps
    // `data` undefined in that case, which is exactly the falsy the web layer
    // treats as "no override".
    expect(res.text).toBe('');
    expect(res.body).toEqual({});
  });

  it('rejects a NEW_ORDER template missing a required variable, naming the missing one', async () => {
    const res = await request(app.getHttpServer())
      .put(`/stores/${storeId}/whatsapp-templates/NEW_ORDER`)
      .set('Cookie', sessionCookie)
      .send({ template: 'Solo los productos: {{items}}' })
      .expect(400);
    expect(res.body.message).toContain('{{orderRef}}');
  });

  it('rejects a PAYMENT_REMINDER template missing a required variable', async () => {
    await request(app.getHttpServer())
      .put(`/stores/${storeId}/whatsapp-templates/PAYMENT_REMINDER`)
      .set('Cookie', sessionCookie)
      .send({ template: 'Pedido {{orderRef}}' })
      .expect(400);
  });

  it('rejects an unknown message type', async () => {
    await request(app.getHttpServer())
      .put(`/stores/${storeId}/whatsapp-templates/ORDER_INQUIRY`)
      .set('Cookie', sessionCookie)
      .send({ template: 'Hola {{orderRef}}' })
      .expect(400);
  });

  it("rejects a non-owner saving a template for someone else's store", async () => {
    await request(app.getHttpServer())
      .put(`/stores/${storeId}/whatsapp-templates/NEW_ORDER`)
      .set('Cookie', otherSessionCookie)
      .send({ template: 'Pedido {{orderRef}} {{items}}' })
      .expect(403);
  });

  it('saves a valid template and returns it on GET, matching the response DTO', async () => {
    const template =
      '*Nuevo pedido en {{storeName}}* #{{orderRef}}\n{{items}}\nTotal: {{totalAmount}} {{currency}}';
    const putRes = await request(app.getHttpServer())
      .put(`/stores/${storeId}/whatsapp-templates/NEW_ORDER`)
      .set('Cookie', sessionCookie)
      .send({ template })
      .expect(200);
    assertMatchesSchema(putRes.body, templateSchema, openapi.components);
    expect(putRes.body.template).toBe(template);

    const getRes = await request(app.getHttpServer())
      .get(`/stores/${storeId}/whatsapp-templates/NEW_ORDER`)
      .set('Cookie', sessionCookie)
      .expect(200);
    assertMatchesSchema(getRes.body, templateSchema, openapi.components);
    expect(getRes.body.template).toBe(template);
  });

  it("checkout renders the store's custom NEW_ORDER template in the seller-bound WhatsApp URL", async () => {
    const checkoutRes = await request(app.getHttpServer())
      .post(`/stores/${storeSlug}/checkout`)
      .send({
        deliveryMethodType: 'PICKUP',
        customerPhone: '+51911111111',
        customerName: 'Jane',
        items: [{ productId, variantId: productVariantId, quantity: 1 }],
      })
      .expect(201);
    const whatsappUrl = checkoutRes.body.whatsappUrl as string;
    orderIds.push(checkoutRes.body.order.id);

    expect(whatsappUrl).toContain(
      encodeURIComponent('*Nuevo pedido en E2E Store*'),
    );
    expect(whatsappUrl).toContain(encodeURIComponent('Total: 25.00 PEN'));
    // The hardcoded default's distinctive marker must not be present.
    expect(whatsappUrl).not.toContain(encodeURIComponent('Ref: #'));
  });

  it("checkout for a store with no override keeps today's exact default message (regression)", async () => {
    // A second store that never touches the templates feature.
    const noOverrideSlug = `whatsapp-default-${runId}`;
    const storeRes = await request(app.getHttpServer())
      .post('/stores')
      .set('Cookie', sessionCookie)
      .send({
        name: 'Default Store',
        slug: noOverrideSlug,
        whatsappNumber: '+51900000001',
      })
      .expect(201);
    const noOverrideStoreId = storeRes.body.id;

    try {
      const productRes = await request(app.getHttpServer())
        .post(`/stores/${noOverrideStoreId}/products`)
        .set('Cookie', sessionCookie)
        .send({ name: 'Plain Product', price: 10, currency: 'PEN', stock: 5 })
        .expect(201);
      await request(app.getHttpServer())
        .patch(
          `/stores/${noOverrideStoreId}/products/${productRes.body.id}/publish`,
        )
        .set('Cookie', sessionCookie)
        .expect(200);

      const checkoutRes = await request(app.getHttpServer())
        .post(`/stores/${noOverrideSlug}/checkout`)
        .send({
          deliveryMethodType: 'PICKUP',
          customerPhone: '+51922222222',
          items: [
            {
              productId: productRes.body.id,
              variantId: productRes.body.variants[0].id,
              quantity: 1,
            },
          ],
        })
        .expect(201);
      const whatsappUrl = checkoutRes.body.whatsappUrl as string;
      orderIds.push(checkoutRes.body.order.id);

      expect(whatsappUrl).toContain(
        encodeURIComponent('*Nuevo pedido en Default Store*'),
      );
      expect(whatsappUrl).toContain(encodeURIComponent('Ref: #'));
      expect(whatsappUrl).toContain(
        encodeURIComponent('Entrega: Retiro presencial'),
      );
    } finally {
      // Order rows must go first — OrderItem.productId blocks deleting the
      // product (and then the store) this store owns.
      await prisma.orderItem.deleteMany({
        where: { orderId: { in: orderIds } },
      });
      await prisma.order.deleteMany({
        where: { id: { in: orderIds } },
      });
      orderIds.length = 0;
      await prisma.notification.deleteMany({
        where: { storeId: noOverrideStoreId },
      });
      await prisma.whatsAppMessageTemplate.deleteMany({
        where: { storeId: noOverrideStoreId },
      });
      await prisma.paymentMethodConfig.deleteMany({
        where: { storeId: noOverrideStoreId },
      });
      await prisma.deliveryMethodConfig.deleteMany({
        where: { storeId: noOverrideStoreId },
      });
      await prisma.productVariant.deleteMany({
        where: { storeId: noOverrideStoreId },
      });
      await prisma.product.deleteMany({
        where: { storeId: noOverrideStoreId },
      });
      await prisma.store.deleteMany({ where: { id: noOverrideStoreId } });
    }
  });
});
